### ISSUE TITLE
Support `aqua cp` command

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1042]
## Feature Overview

Add a subcommand `cp` to copy files to the specified directory.

## Why is the feature needed?

> Please explain the problem you want to solve.

This is useful to execute tools without aqua.
Especially, this is useful to install tools in Docker images.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ aqua cp [-o <target directory>] command [command ...]
```

e.g.

```console
$ aqua cp terraform reviewdog actionlint
```

By default, files are copied at `dist` directory.

## Reference

* https://github.com/aquaproj/aqua-docker

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/1061

**Comment by lukasmrtvy** [comment]
@suzuki-shunsuke would be nice to support wildcard `*` ,  or some arg like `--arg`

```
aqua cp * -o /usr/local/bin/
```

ideas?

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
Could you create an issue with the [issue template](https://github.com/aquaproj/aqua/issues/new?assignees=&labels=&template=Feature_Request.md)?
