### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by frezbo** [aquaproj/aqua#1076]
## Feature Overview

aqua is a tool that I use daily and has become part of my development machine setup workflow. As a happy user I would like to help the maintainer keep the project going forward.

It would be nice if Github sponsors for the project could be set up.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I'm really glad to hear that.

Let me consider about it.

**Comment by suzuki-shunsuke** [comment]
I'm working on this issue.
I started my GitHub Sponsor. https://github.com/sponsors/suzuki-shunsuke
And GitHub Sponsors profile of this project is waiting to be reviewed by GitHub.

**Comment by suzuki-shunsuke** [comment]
aquaproj has been approved for GitHub Sponsors 🎉
https://github.com/sponsors/aquaproj
