### ISSUE TITLE
Improve the handling of GitHub API Rate Limit

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1099]
## Feature Overview

1. Call GitHub API without Access Token
2. If `1` fails, call GitHub API with Access Token

## Why is the feature needed?

> Please explain the problem you want to solve.

Recently, rate limit errors occur at several times at aqua-registry.

* https://github.com/aquaproj/aqua-registry/pull/5345#issuecomment-1207698294

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

Nothing.

## Reference

* https://pkg.go.dev/github.com/google/go-github/v45/github#hdr-Rate_Limiting
* https://pkg.go.dev/github.com/google/go-github/v45/github#AbuseRateLimitError
* https://pkg.go.dev/github.com/google/go-github/v45/github#RateLimitError
  * We can get the reset time and remaining time

**Comment by nikolay** [comment]
Is there a way to pass a GitHub token now?

**Comment by suzuki-shunsuke** [comment]
You can pass a GitHub Token with environment variables `GITHUB_TOKEN` and `AQUA_GITHUB_TOKEN`.

**Comment by suzuki-shunsuke** [comment]
This issue is old and I completely forgot this issue.
Recently I don't face the rate limiting issue.
So maybe we can close this issue for now.
