### ISSUE TITLE
zips

### ISSUE THREAD

**Issue by gedw99** [aquaproj/aqua#1566]
wondering is zip files or tar files can be used with this ?

The use case is that some binary dependencies that i need to pull are a group of file and not just a single binary.

also dies this only support golang based binaries because i also wanted to do wasm for example.

**Comment by suzuki-shunsuke** [comment]
aqua supports zip and tar files.

And aqua supports not only Go based binaries but also shell scripts, Rust, and so on.

> i also wanted to do wasm for example.

I'm sorry but I'm not familiar with wasm.

Could you tell me tools that you want to install by aqua?

**Comment by suzuki-shunsuke** [comment]
Closed an inactive issue.
