### ISSUE TITLE
Is it possible that aqua will support .dmg files in the future?

### ISSUE THREAD

**Issue by u-yas** [aquaproj/aqua#1706]
## Feature Overview
I want to make tools in .dmg files available in aqua

## Why is the feature needed?

> Please explain the problem you want to solve.
>
Some cli tools are distributed in darwin as .dmg files only. (For example, [in the case of AWS-Vault](https://github.com/99designs/aws-vault/releases/tag/v7.0.1)).
If an aqua user requests the cli author to distribute binaries for darwin, the author will say, "Why should I release a duplicate package when I distribute a dmg file for darwin?" This would be the case. I too do not think this solution is reasonable.
Maybe the best way to make everyone happy in such a case is to use a version manager like aqua to handle it.

I think it is technically possible to support dmg files, since dmg files themselves can be handled by brew cli and so on.
If I make a pull request, is it possible for aqua to accept this change?

## Does the feature include Breaking Changes?
No, it is only an additional feature to support .dmg extensions, so aqua does not expect it to affect others

## Example Code

```

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal and question.
I'm not familiar with `dmg` format, but if `dmg` format can be unarchived to the specific directory (under `AQUA_ROOT_DIR/pkgs`) same as other formats such as tar.gz and zip by Go, aqua would be able to support dmg file.

According wikipedia, `Apple has not released any documentation on the format`.

https://en.wikipedia.org/wiki/Apple_Disk_Image

> Apple has not released any documentation on the format, but attempts to reverse engineer parts of the format have been successful.

I can't find Go library to unarchive the dmg format.
aqua uses [mholt/archiver](https://github.com/mholt/archiver) to unarchive files, but this library doesn't support dmg format.

So I thought it is difficult to support dmg format.

But your comment is interesting.

> I think it is technically possible to support dmg files, since dmg files themselves can be handled by brew cli and so on.

Maybe dmg files can be handled with Go, but I'm not sure.

**Comment by suzuki-shunsuke** [comment]
BTW, today there was a timely pull request.

- https://github.com/aquaproj/aqua-registry/pull/10488

This pull request was closed because aqua doesn't support dmg files.

**Comment by u-yas** [comment]
I read a little bit of the brew source code, but it seemed to be processed in the following places
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/unpack_strategy/dmg.rb
I'm not very familiar with the ruby language, but as far as I can see, it seems that external commands such as mkbom, hdutil, and ditto are used.

> aqua doesn't run external commands as much as possible for security, portability, and maintainability.
>
Considering the following points, it may be difficult to support dmg files in aqua...

**Comment by suzuki-shunsuke** [comment]
> aqua doesn't run external commands as much as possible for security, portability, and maintainability.

This isn't mandatory.
I think we can allow commands if they are definitely installed in macOS and there is no security concern.

In fact, aqua allows some external commands such as `go install` and `cosign verify-blob`.
