### ISSUE TITLE
Improve the user experience of non Standard Registries

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1789]
## Feature Overview

Improve the user experience when they use non Standard Registries.

## Current situation

[From aqua v2, you have to define the policy to use non Standard Registries](https://aquaproj.github.io/docs/reference/upgrade-guide/v2/only-standard-registry-is-allowed-by-default).

At the moment, you have to do the following things.

1. Create a policy file
1. Set `AQUA_POLICY_CONFIG`

```console
$ aqua init-policy # aqua-policy.yaml is created
$ vi aqua-policy.yaml # Allow non Standard Registries
$ export AQUA_POLICY_CONFIG=$PWD/aqua-policy.yaml:$AQUA_POLICY_CONFIG
```

## How to Improve the user experience

For example, [direnv](https://github.com/direnv/direnv)'s `direnv allow` command may be helpful.
I'm considering if we can allow non Standard Registries by similar user interface.

## Why is the feature needed?

> Please explain the problem you want to solve.

From aqua v2, you have to define the policy to use non Standard Registries.
We thought

- This change was necessary to improve the security
- Almost users didn't have to use non Standard Registries, so this change didn't harm the user experience for almost users

But now, I have a concern maybe this change made the user experience worse than I expected.

So I'm considering improving the user experience without the security risk.

## Does the feature include Breaking Changes?

Unsure.

## Example Code

> command and configuration

```console
$ 
```

```yaml

```

## Reference

- [Policy as Code](https://aquaproj.github.io/docs/reference/security/policy-as-code/)

**Comment by suzuki-shunsuke** [comment]
# Idea 1. Add the global policy file and add `allow` command

- aqua reads the global policy file `$AQUA_ROOT_DIR/policy.yaml` automatically
- `aqua allow` command creates or updates the global policy file
  - `aqua allow` command allows Registries used in the given configuration files

```console
$ aqua allow <configuration file path> [<configuration file path>...]
```

By this command, users can configure the policy easily without knowing about the policy well.

**Comment by suzuki-shunsuke** [comment]
# Idea 2. Normalize Registry content and keep the list of allowed Registries

```console
$ aqua allow aqua.yaml
```

1. Normalize local Registry and generate a hash of the normalized local Registry
1. Create a file whose name is the generated hash in `$AQUA_ROOT_DIR/allowed-registries/<hash>`

aqua checks if the hash exists when installs and executes packages and if the hash doesn't exist the command would fail.

Remaining issues are

- How to treat `github_content` Registries

I found this isn't secure because we can tamper `aqua.yaml`.
We should allow Registries instead.

```console
$ aqua allow registry.yaml
```

```console
# <repo owner>/<repo name>[@<ref>]:<path>
$ aqua allow \
  suzuki-shunsuke/private-registry:registry.yaml \
  suzuki-shunsuke/private-registry:.aqua/registry.yaml \
  suzuki-shunsuke/private-registry@v0.1.0:registry.yaml \
  'suzuki-shunsuke/private-registry@semver(">= 3.0.0"):registry.yaml'
```

**Comment by suzuki-shunsuke** [comment]
# Idea 3. Allow local Registry by not content but path

```console
$ aqua allow [-content] <registry file path>
```

```console
$ aqua allow github_content:<repo owner>/<repo name>[@<ref>]:<path>
```

```
$AQUA_ROOT_DIR/allowed-registries/
  local/
    <hash of path>
    <hash of content>
  github_content.json
```

**Comment by suzuki-shunsuke** [comment]
# Idea 4 = Idea 1 + 3

```console
$ aqua init-policy
$ aqua set-policy aqua.yaml
$ aqua allow aqua-policy.yaml
```

**Comment by suzuki-shunsuke** [comment]
# Introduce Global Policy and new commands to manage Policy

Global Policy is 

Add new commands `set-policy` and `apply-policy`.

`set-policy` creates or updates a policy file based on `aqua.yaml`. This command enables you to generate a Policy file easily. This is also alternative of `init-policy`.
`apply-policy` applies a Policy file to the global Policy. You don't have to configure the environment variable `AQUA_POLICY_CONFIG`.

**Comment by suzuki-shunsuke** [comment]
Global Policy is different from the project specific Policy.
Global Policy doesn't meet the use case like you want to allow this policy only in this project, or you want to disallow this policy only in this project.

**Comment by suzuki-shunsuke** [comment]
# Idea 5

As I mentioned in https://github.com/aquaproj/aqua/issues/1789#issuecomment-1482087048 , Global Policy is different from the project specific Policy. And applying the Policy for the project to Global Policy is hard to treat the project specific rule.

So I'm newly considering creating policy files per `aqua.yaml` in `AQUA_ROOT_DIR` by `aqua apply-policy` command.

```
AQUA_ROOT_DIR/policies/<aqua.yaml's absolute path>
```

**Comment by suzuki-shunsuke** [comment]
Everytime we fix a policy, we have to run `aqua apply-policy` but we probably would forget to run `aqua apply-policy`.
So it is useful that `set-policy` updates the policy in `AQUA_ROOT_DIR` too.

**Comment by suzuki-shunsuke** [comment]
`aqua apply-policy -g` applies the policy to the global configuration.

**Comment by suzuki-shunsuke** [comment]
1. `AQUA_ROOT_DIR/policies/<aqua.yaml's absolute path>`
1. `AQUA_ROOT_DIR/aqua-policy.yaml`
1. `AQUA_POLICY_CONFIG`

If there are multiple policy types, it would be difficult to understand the current policy configuration.

**Comment by suzuki-shunsuke** [comment]
# aqua-policy.yaml in the Git Repository root

aqua reads the policy file in the Git Repository root automatically.
You don't have to define the environment variable `AQUA_POLICY_CONFIG`.
The policy file path is determined and can't be changed, so you can prevent the policy file from being modified by GitHub's CODEOWENRS.

And you have to allow the policy file the policy file.

**Comment by suzuki-shunsuke** [comment]
# Proposal 1. Git Repository root's policy file and allow-policy and disallow-policy command

## Who needs this feature

If you don't use non Standard Registry, you don't have to mind this feature.
Almost users would not have to use non Standard Registry, so almost users don't have to mind this feature.
This feature is for users who use non Standard Registries.

## Overview

I propose `Git Repository root's policy file` and `allow-policy` and `disallow-policy` command.
`Git Repository root's policy file` is a Policy file in the Git Repository root directory.

```
.git/ # Git Repository root
aqua-policy.yaml
.aqua-policy.yaml
aqua/aqua-policy.yaml
.aqua/aqua-policy.yaml
```

⚠️ The file extension `.yml` isn't supported at the moment.

Before aqua executes or installs packages, aqua finds `Git Repository root's policy file`.
aqua finds the Git repository root directory from the current directory to the root directory recursively.

If `Git Repository root's policy file` isn't found, it is same as usual.
If `Git Repository root's policy file` is found, aqua checks if the policy file is already allowed or not.
If `Git Repository root's policy file` is already allowed, aqua uses `Git Repository root's policy file` as Policy.
If `Git Repository root's policy file` isn't allowed, aqua outputs the warning and ignores `Git Repository root's policy file`.

`allow-policy` command is a command to allow a policy file.

```console
$ aqua allow-policy [<policy file path>]
```

If no argument is given, aqua allows `Git Repository root's policy file`.

Even if you allow a policy file once, you have to allow the policy file again if the policy file is modified.

`disallow-policy` command is a command to disallow a policy file.

```console
$ aqua disallow-policy [<policy file path>]
```

If no argument is given, aqua allows `Git Repository root's policy file`.

`disallow-policy` is used to ignore `Git Repository root's policy file` and suppress the warning.

## How to use

1. Add `Git Repository root's policy file` to your Git repository
1. Run `aqua allow-policy` in the repository

## Why this feature is needed

To improve the user experience of non Standard Registries.
To set up Policy easily keeping the security.

To use non Standard Registries, you had to set the environment variable `AQUA_POLICY_CONFIG`.
But it is bothersome, especially in the team development because all members have to set the environment variable `AQUA_POLICY_CONFIG`.
Some tools such as `direnv` are useful to set environment variables, but it is undesirable to ask users to install additional tools for aqua.

So we would like to apply a policy without `AQUA_POLICY_CONFIG`, but at the same time we have to keep the security.

## Design consideration

Sometimes security and convenience are conflicted, so we have to be careful not to harm security for convenience.
To keep the security, I think aqua should ask users to allow `Git Repository root's policy file` explicitly.
This means aqua should not apply `Git Repository root's policy file` without user's approval.
So I propose to add a command `allow-policy` and ask users to allow `Git Repository root's policy file` using this command.

## Getting Started

1. create a Git repository
1. create aqua.yaml and aqua-policy.yaml
1. create a local Registry registry.yaml
1. update aqua.yaml
1. Confirm the warning
1. try to use a local Registry
1. Run disallow-policy
1. try to use a local Registry
1. Run allow-policy

Coming soon.

## Detail for maintainers

⚠️ This is the implementation detail. You shouldn't depend on it and the detail may be changed.

aqua creates two types of files.

1. `$AQUA_ROOT_DIR/policies/<absolute path of policy file>`: Copy of `Git Repository root's policy file`
1. `$AQUA_ROOT_DIR/policy-warnings/<absolute path of policy file>`: Disallowed `Git Repository root's policy file`. The file content is empty

`aqua allow-policy` creates `Copy of Git Repository root's policy file` and removes `Disallowed Git Repository root's policy file`.
`aqua disallow-policy` removes `Copy of Git Repository root's policy file` and creates `Disallowed Git Repository root's policy file`.

**Comment by suzuki-shunsuke** [comment]
# Proposal 2. Support `set-policy` command to create or update a Policy file easily

## Overview

I propose to add a new command `set-policy` to create or update a Policy file easily.

```
aqua set-policy [<policy file path>]
```

This command reads `aqua.yaml` and create or update `aqua-policy.yaml`.
If no policy file path is given, aqua searches `Git Repository root's policy file`.
If `Git Repository root's policy file` isn't found, aqua creates or updates `aqua-policy.yaml` in the current directory.

## How to use

Run `aqua set-policy` to create or update a Policy file.

## Why this feature is needed

To create or update a Policy file easily.
Users don't have to learn how to write a Policy file basically.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/1808
- https://github.com/aquaproj/aquaproj.github.io/pull/352

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.

About the automatic update of checksum, please see https://aquaproj.github.io/docs/guides/checksum .

**Comment by suzuki-shunsuke** [comment]
I've published prerelease versions.

- https://github.com/aquaproj/aqua/releases/tag/v2.3.0-7
- https://github.com/aquaproj/aqua-installer/releases/tag/v2.0.3-1
- https://github.com/aquaproj/update-checksum-workflow/releases/tag/v0.1.5-1

I've introduced them to aqua-registry. https://github.com/aquaproj/aqua-registry/pull/11359

And I've written the document.

- https://github.com/aquaproj/aquaproj.github.io/pull/352
- https://github.com/aquaproj/aquaproj.github.io/blob/1adca2d9d3d01c1e70c3adb4ca99b9a7cd29fde7/docs/guides/policy-as-code.md
- https://github.com/aquaproj/aquaproj.github.io/blob/1adca2d9d3d01c1e70c3adb4ca99b9a7cd29fde7/docs/reference/security/policy-as-code/git-policy.md

I really appreciate if you try them and give us your feedback!

**Comment by suzuki-shunsuke** [comment]
- [ ] Release aqua v2.3.0
- [ ] Merge https://github.com/aquaproj/aqua-installer/pull/403
- [ ] Release aqua-installer v2.1.0
- [ ] Merge https://github.com/aquaproj/update-checksum-workflow/pull/19
- [ ] Release update-checksum-workflow v0.1.5
- [ ] Merge https://github.com/aquaproj/aquaproj.github.io/pull/352

**Comment by sheldonhull** [comment]
Thank you as always for helping move things forward. 
While I saw the github action for updating checksums, I felt worth mentioning as not all things are based on github for folks. For example i use a mix of Azure Repos, some might use Gitlab/bitbucket. It's good to have the checksum update be a smooth process for everyone regardless of github usage. 
I'll be sure to look at the latest updates though and keep working forward and provide more feedback as I find it. Cheers and thanks again!

**Comment by suzuki-shunsuke** [comment]
Thank you always for your feedback.
I haven't used Azure Repos, GitLab, BitBucket, and so on. So I'm not familiar with them but if they have features like GitHub Actions maybe we can provide tools for them.
I'll take a look when I have a time. Your contribution is also welcome.

BTW, do you have any feedback against the new feature?

- https://aquaproj.github.io/docs/guides/policy-as-code
- https://aquaproj.github.io/docs/reference/security/policy-as-code/git-policy

**Comment by suzuki-shunsuke** [comment]
Created issues.

- https://github.com/aquaproj/aqua/issues/1855
- https://github.com/aquaproj/aqua/issues/1856
- https://github.com/aquaproj/aqua/issues/1857
