### ISSUE TITLE
Infinite Failure Loop Due to Global Policy And Loading Policy Env Variable via Direnv

### ISSUE THREAD

**Issue by sheldonhull** [aquaproj/aqua#1896]
- Use a global configuration that includes install direnv.
- Create a `.envrc` for your project.
- Use a global configuration file for tools and this also has a policy file set so custom go packages can be installed using `aqua install --all`. This means for the individual project I need to append the current project policy so direnv will load it. 

```shell
source_env_if_exists ${HOME}/.envrc
export AQUA_POLICY_CONFIG="${PWD}/aqua-policy.yaml:${AQUA_POLICY_CONFIG}"
```

## result

Since `direnv` must be allowed to run on any change, the resulting failure for the policy file to be designated in current session until direnv allow is run results in an infinite loop being blocked by permissions.

I need to go reread docs to see if any changes, but at the last read I think the environment variable was required instead of it autodetecting the policy config in the directory.

```shell
echo $AQUA_POLICY_CONFIG             
/Users/sheldon.hull/.local/share/chezmoi/aqua-policy.yaml:/Users/sheldon.hull/.local/share/chezmoi/aqua-policy.yaml:/Users/sheldon.hull/.config/aqua/aqua-policy.yaml
```

<img width="1706" alt="CleanShot 2023-04-20 at 12 19 05@2x" src="https://user-images.githubusercontent.com/3526320/233440983-eed4c5e0-7156-4072-96da-101215bc8803.png">

**Comment by sheldonhull** [comment]
One thing I'm possibly mixing up is the global packages setup + policy config. I have chezmoi deploying to the global location and these are set in the environment (.zshenv). 

Starship is failing to work and wondering if has something to do with the scope that starship runs at (which doesn't make sense to me). It's also not a local package, but instead a global one from standard registry.
<img width="276" alt="CleanShot 2023-04-20 at 12 29 42@2x" src="https://user-images.githubusercontent.com/3526320/233443126-c141a050-1f00-42f9-bfd9-faf7518e94bd.png">

**Comment by sheldonhull** [comment]
Ok... i see you did a great job bringing in the concept of Git repository config being detected. Problem solved there!

Only remaining concern... what's the proper way to allow my global configuration policy then?

**Comment by suzuki-shunsuke** [comment]
> Only remaining concern... what's the proper way to allow my global configuration policy then?

If you want to allow your custom Registries globally, please set the environment variable `AQUA_POLICY_CONFIG`.

e.g.

```
$HOME/
  your-custom-registry/
    registry.yaml
    aqua-policy.yaml
```

$HOME/your-custom-registry/aqua-policy.yaml

```yaml
---
# aqua Policy
# https://aquaproj.github.io/
registries:
# Example
  - name: local
    type: local
    path: registry.yaml
  - type: standard
    ref: semver(">= 3.0.0")
packages:
  - registry: local # allow all packages in the Registry
  - registry: standard
```

```sh
export AQUA_POLICY_CONFIG=$HOME/your-custom-registry/aqua-policy.yaml:$AQUA_POLICY_CONFIG
```
