### ISSUE TITLE
Suggestion to consider new default for aqua init to be subdirectory `.aqua`

### ISSUE THREAD

**Issue by sheldonhull** [aquaproj/aqua#1902]
Consider making the new default `.aqua` directory. Continue to support the other ways, as you already do, but having `aqua init` generate an `aqua.yaml` as well as possibly the `aqua-policy.yaml` in the nested directory would keep the project files a little clearer. I especially like this because the `registry.yaml` doesn't have aqua in the name and for those not familiar with aqua it's less obvious it belongs to the same set of configuration files. Since aqua now has several files that can be included in projects (3-4 if you use a registry and checksums), this is a bit better onboarding experience.

**Comment by suzuki-shunsuke** [comment]
Thank you for your suggestion.

You suggest to change the behaviour of `aqua init` to create a directory `.aqua` and file `.aqua/aqua.yaml`, right?
I don't like the idea `hidden file` so I don't want to make `.aqua` by default.
