### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2155]
- Improve the maintainability
- Achieve the goal that everyone can contribute to aqua itself

We have some feature requests now, but I'd like to refactor aqua first.

The current issues that

- codes about a specific logic are dispersed across multiple packages, so we need to check and fix multiple packages to fix a specific logic
- The complexity is high because code for specific logic is branched by `if` statements
- The abstraction of package types is not good so the meaning of some APIs is ambiguous for some package types
- code comment is inadequate

So I'd like to create new Go packages for each package type and put together code for a specific logic, and redesign the API of each package type.

**Comment by gedw99** [comment]
Is this going to be a v2 with new paths ? 

Asking because I would like to also contribute a d I found the API and code base to be , no offense, but really hard work.

even the cli naming conventions are very obtuse

**Comment by suzuki-shunsuke** [comment]
I'm sorry but I can't understand your question well.

aqua is already v2. And this issue is for a refactoring of the internal code, so we don't make any breaking changes.

And we don't have a plan for aqua v3 yet.

**Comment by suzuki-shunsuke** [comment]
I close this issue once because this is inactive.
