### ISSUE TITLE
How is aqua-proxy updated?

### ISSUE THREAD

**Issue by frezbo** [aquaproj/aqua#2266]
### Free Text

`aqua update-aqua` doesn't seem to update `aqua-proxy`.  I usually end up deleting it and running `aqua install <something>` which triggers a re-download of latest aqua-proxy

**Comment by suzuki-shunsuke** [comment]
Hmm. I'm curious why you and some users create issues mistakenly. 🤔 
I expect you find the warning before creating issues.

https://github.com/aquaproj/aqua/issues/new?assignees=&labels=&projects=&template=general.yml

<img width="976" alt="image" src="https://github.com/aquaproj/aqua/assets/13323303/98855d73-f608-413a-8387-5f733e1a9d5f">

Do you guys create issues via API or something?

**Comment by frezbo** [comment]
> Hmm. I'm curious why you and some users create issues mistakenly.

apologies, honestly it's just the habit of filing issues (when discussions were not a thing) without reading guidelines. I'll make sure to spend time reading going forward. Agree that discussions are way better

**Comment by suzuki-shunsuke** [comment]
I see. Thank you for your explanation.
No worries. I just wondered if our measures weren't enough.
