### ISSUE TITLE
Support disabling the verification with Cosign and slsa-verifier

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2633]
### Feature Overview

Support disabling the verification with Cosign and slsa-verifier.

### Why is the feature needed?

Original discussion: https://github.com/orgs/aquaproj/discussions/2631

Cosign and sla-verifier access some endpoints such as `oauth2.sigstore.dev` and `fulcio.sigstore.dev`.
So to use them you need to allow the access to these endpoints.

But in some use cases you can't or don't want to do that.
For example, your company's network policy might not allow the access to these endpoints.

To resolve the issue, this issue proposes to support disabling the verification with Cosign and slsa-verifier.

### Workaround

There is no workaround.

### Example Code

1. Add command line options

e.g.

```sh
aqua [-disable-cosign] [-disable-slsa] i
```

2. Add environment variables

e.g.

```sh
env AQUA_DISABLE_COSIGN=true AQUA_DISABLE_SLSA=true aqua i
```

### Note

This feature isn't good in terms of security,
but I don't think the disabling the verification with Cosign and slsa-verifier causes the security threats immediately.
And most packages don't support Cosign and slsa-verifier, so the affect is limited.

I don't want to require users to allow the access to those endpoints.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/2634

**Comment by suzuki-shunsuke** [comment]
@tuananh
Could you try https://github.com/aquaproj/aqua/releases/tag/v2.22.0-1 ?
If there is no problem, we'll merge #2634 and release v2.22.0.

**Comment by tuananh** [comment]
it seems to work. thanks a lot :)

**Comment by suzuki-shunsuke** [comment]
Thank you!

v2.22.0 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.22.0

**Comment by suzuki-shunsuke** [comment]
aqua-installer v2.3.0 is out 🎉

https://github.com/aquaproj/aqua-installer/releases/tag/v2.3.0

To disable the verification when you install aqua with aqua-installer, please use aqua-installer v2.3.0 or newer and set the environment variables `AQUA_DISABLE_COSIGN` and `AQUA_DISABLE_SLSA`.

```sh
export AQUA_DISABLE_COSIGN=true
export AQUA_DISABLE_SLSA=true
./aqua-installer
```
