### ISSUE TITLE
failed to download the latest standard registry as it is too large

### ISSUE THREAD

**Issue by sheldonhull** [aquaproj/aqua#2713]
## package name

- `starship/starship@v1.17.1`

## Important Factoids

- I hadn't run `aqua update` against my packages for a bit, so this was the latest version that got picked up.
- Upstream project... [prior release](https://github.com/starship/starship/releases/tag/v1.15.0) vs [current release](https://github.com/starship/starship/releases/tag/v1.17.1). The aarch64 is now 10.3MB while prior version is 2.46MB. This is an increase of 318%. While it might be an upstream issue to try and fix, Aqua might need improved logic to handle changing to the other download method of contents per API message when it fails due to size. 
- Note, I'm seeing this issue in some others that aren't a huge increase so maybe also an issue in the latest aqua version and this starship binary issue was related but not the root. Example, `direnv` is flagging this message as well.
- EDIT: Also reverted to [v2.23.0](https://github.com/aquaproj/aqua/releases/tag/v2.23.0) so maybe it's a GitHub API change? 

## aqua version

Please use the latest version.

```console
aqua -v
aqua version 2.23.1 (65fb59915fced5e16413e59cd17b3f0a1b42b972)
```

## Environment

- OS (Windows, Linux, macOS, etc): `macOS`
- CPU Architecture (amd64, arm64, etc): `arm64`

## How to reproduce

- aqua.yaml
- executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
checksum:
  enabled: true
  require_checksum: false
registries:
  - type: standard
    ref:  # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: registry.yaml
packages:
  - name: starship/starship@v1.17.1
```

```console
aqua i
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
aqua i

DEBU[0000] install the proxy                             aqua_version=2.23.1 env=darwin/arm64 package_name=aqua-proxy package_version=v1.2.5 program=aqua registry=
DEBU[0000] check if aqua-proxy is already installed      aqua_version=2.23.1 env=darwin/arm64 package_name=aqua-proxy package_version=v1.2.5 program=aqua registry=
WARN[0000] The policy file is ignored unless it is allowed by "aqua policy allow" command.

$ aqua policy allow "/Users/$(whoami)/.local/share/chezmoi/.aqua/aqua-policy.yaml"

If you want to keep ignoring the policy file without the warning, please run "aqua policy deny" command.

$ aqua policy deny "/Users/$(whoami)/.local/share/chezmoi/.aqua/aqua-policy.yaml"

   aqua_version=2.23.1 doc="https://aquaproj.github.io/docs/reference/codes/003" env=darwin/arm64 policy_file=/Users/$(whoami)/.local/share/chezmoi/.aqua/aqua-policy.yaml program=aqua
ERRO[0000] install the registry                          aqua_version=2.23.1 env=darwin/arm64 error="get a GitHub Content file content: unsupported content encoding: none, this may occur when file size > 1 MB, if that is the case consider using DownloadContents" program=aqua registry_name=standard
FATA[0000] aqua failed                                   aqua_version=2.23.1 env=darwin/arm64 error="it failed to install some registries" program=aqua
ERRO[0000] install the registry                          aqua_version=2.23.1 env=darwin/arm64 error="get a GitHub Content file content: unsupported content encoding: none, this may occur when file size > 1 MB, if that is the case consider using DownloadContents" exe_name=starship program=aqua registry_name=standard
FATA[0000] aqua failed                                   aqua_version=2.23.1 env=darwin/arm64 error="it failed to install some registries" exe_name=starship program=aqua
ERRO[0000] install the registry                          aqua_version=2.23.1 env=darwin/arm64 error="get a GitHub Content file content: unsupported content encoding: none, this may occur when file size > 1 MB, if that is the case consider using DownloadContents" exe_name=starship program=aqua registry_name=standard
FATA[0000] aqua failed                                   aqua_version=2.23.1 env=darwin/arm64 error="it failed to install some registries" exe_name=starship program=aqua
```

## Expected Behaviour

Starship has typically succeeded.
## Actual Behaviour

```text
ERRO[0000] install the registry                          aqua_version=2.23.1 env=darwin/arm64 error="get a GitHub Content file content: unsupported content encoding: none, this may occur when file size > 1 MB, if that is the case consider using DownloadContents" exe_name=starship program=aqua registry_name=standard
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

```
error="get a GitHub Content file content: unsupported content encoding: none, this may occur when file size > 1 MB, if that is the case consider using DownloadContents"
```

https://github.com/aquaproj/aqua/blob/8caa94e490fc6a321dad708096f6b3e805d6bad1/pkg/download/github_content.go#L56

https://github.com/google/go-github/blob/a25989b0298916f638f33c35429ecda5d6c0850b/github/repos_contents.go#L95

I've seen the same issue in other projects.

Now aqua uses the API [RepositoriesService.GetContents](https://pkg.go.dev/github.com/google/go-github/v60/github#RepositoriesService.GetContents), but I guess we need to use [RepositoriesService.DownloadContents](https://pkg.go.dev/github.com/google/go-github/v60/github#RepositoriesService.DownloadContents) instead.

**Comment by suzuki-shunsuke** [comment]
Oh, I see.

```
ERRO[0000] install the registry
```

starship has nothing to do with this issue.
It failed to download the standard registry.
The standard registry https://github.com/aquaproj/aqua-registry/blob/main/registry.yaml is too large.

**Comment by suzuki-shunsuke** [comment]
I couldn't reproduce the issue with the latest standard registry v4.146.0.

```yaml
registries:
- type: standard
  ref: v4.146.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.44.1
```

```sh
rm -R ~/.local/share/aquaproj-aqua/registries/github_content/github.com/aquaproj/aqua-registry # Remove the standard registry once
aqua i
```

The standard registry was downloaded without any error.
The size is 1.1M.

```console
$ ls -lh ~/.local/share/aquaproj-aqua/registries/github_content/github.com/aquaproj/aqua-registry/v4.146.0/registry.yaml
-rw-r--r-- 1 shunsukesuzuki staff 1.1M  3  2 07:44 /Users/shunsukesuzuki/.local/share/aquaproj-aqua/registries/github_content/github.com/aquaproj/aqua-registry/v4.146.0/registry.yaml
```

It looks weird.
Anyway, I'll try [RepositoriesService.DownloadContents](https://pkg.go.dev/github.com/google/go-github/v60/github#RepositoriesService.DownloadContents).

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/2714

**Comment by suzuki-shunsuke** [comment]
@sheldonhull Could you try [v2.23.2-1](https://github.com/aquaproj/aqua/releases/tag/v2.23.2-1)?

```sh
aqua upa v2.23.2-1
```

**Comment by suzuki-shunsuke** [comment]
v2.23.2 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.23.2
