### ISSUE TITLE
Generate shell completion on `brew install`

### ISSUE THREAD

**Issue by ryota2357** [aquaproj/aqua#2824]
### Feature Overview

`brew install aquaproj/aqua/aqua` does not generate shell completion.

Homebrew has support for handling shell completion in `brew install` (ref: https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method).
Use this to generate shell completion on installation.

### Why is the feature needed?

It is nice that shell completion is enabled simply by installing `aqua`.

### Workaround

run manually `source <(aqua completion [bash|zsh])`

### Note

We can customize `aqua.rb` on `brew.install` entry in `.goreleaser` but I found that adding this entry is not enough, so I created an issue for now.

I will create PR soon.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

📝

https://aquaproj.github.io/docs/reference/config/shell-completion/
https://goreleaser.com/customization/homebrew/

```yaml
    # Additional install instructions so you don't need to override `install`.
    #
    # Template: allowed
    # Since: v1.20
    extra_install: |
      bash_completion.install "completions/foo.bash" => "foo"
      man1.install "man/foo.1.gz"
      # ...
```

**Comment by suzuki-shunsuke** [comment]
> Homebrew has support for handling shell completion in brew install (ref: https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method).
Use this to generate shell completion on installation.

I'd like to know the behavior of this feature.

1. Does this update .bashrc or .zshrc automatically when we run `brew install aquaproj/aqua/aqua`?
1. Does Homebrew update the configuration file of the default shell?
1. If the shell configuration file includes the shell completion setting, does `brew install aquaproj/aqua/aqua` skip adding the shell completion?

**Comment by ryota2357** [comment]
> 1. Does this update .bashrc or .zshrc automatically when we run brew install aquaproj/aqua/aqua?

No, Homebrew install shell comp to `/opt/homebrew/share/zsh/site-functions` for arm-mac zsh.　 bash as well will put the completion files in a homebrew managed directory.

> 2. Does Homebrew update the configuration file of the default shell?

No.

> 3. If the shell configuration file includes the shell completion setting, does brew install aquaproj/aqua/aqua skip adding the shell completion?

No, but I think it does not cause probrem because user can manage completion priority via `$FPATH`

**Comment by suzuki-shunsuke** [comment]
I see. Thank you for your explanation.
Looks good.

**Comment by suzuki-shunsuke** [comment]
v2.27.1 is out 🎉

https://github.com/aquaproj/aqua/releases/tag/v2.27.1

Let's check if `brew install` works as expected.

**Comment by ryota2357** [comment]
I updated aqua to 2.27.1 by homebrew, and I got the completion.
Thank you for merge and review!

**Comment by suzuki-shunsuke** [comment]
I've also confirmed zsh completion works.
Thank you for your contribution!
