### ISSUE TITLE
Empty registry.yaml.json file created when conversions fail

### ISSUE THREAD

**Issue by ka2n** [aquaproj/aqua#2829]
### aqua info

```console
$ aqua info
{
  "version": "2.27.1",
  "commit_hash": "67f130be65c42150112baa1ed83d0c2ff54e394d",
  "os": "linux",
  "arch": "amd64",
  "pwd": "/home/(USER)/src/github.com/aquaproj/aqua",
  "root_dir": "/home/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_GLOBAL_CONFIG": "/home/(USER)/.config/aquaproj-aqua/aqua.yaml"
  },
  "config_files": [
    {
      "path": "/home/(USER)/src/github.com/aquaproj/aqua/aqua/aqua.yaml"
    }
  ]
}
```

### Overview

I am encountering an intermittent issue where `registry.yaml.json` is created as an empty file.

### How to reproduce

I just found that the file was empty and I couldn't reproduce a similar situation!

aqua.yaml

```yaml
registries:
  - type: standard
    ref: v4.158.0 # renovate: depName=aquaproj/aqua-registry
```

Executed command and output

```console
$ cd (PROJECT DIR)
$ [WARN] - (starship::utils): Executing command "/home/(USER)/.local/share/aquaproj-aqua/bin/buf" timed out.                     [WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.
↑ aqua killed?

$ aqua i -l
ERRO[0000] install the registry                          aqua_version=2.27.1 env=linux/amd64 error="parse the registry configuration as JSON: EOF" program=aqua registry_name=standard
FATA[0000] aqua failed                                   aqua_version=2.27.1 env=linux/amd64 error="it failed to install some registries" program=aqua
```

### Expected behaviour

`registry.yaml` will be converted into `registry.yaml.json`

### Actual behaviour

Empty `registry.yaml.json` was created.

### Note

This seems to occur when the conversion from `registry.yaml` to JSON fails; instead of deleting the failed file, the program merely closes it with `jsonFile.Close()`.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
1. If aqua fails to convert YAML to JSON, aqua should remove the JSON file and continue the process
1. If aqua fails to parse a JSON file, aqua should remove the JSON file and read YAML file and generate a JSON file and continue the process

**Comment by suzuki-shunsuke** [comment]
> If aqua fails to convert YAML to JSON, aqua should
> 
> 1. remove the JSON file
> 2. output warning or debug log
> 3. continue the process
> 
> If aqua fails to parse a JSON file, aqua should
> 
> 1. output warning or debug log
> 2. remove the JSON file
> 3. read YAML file
> 4. generate a JSON file
> 5. continue the process

Only latter is enough.

- - https://github.com/aquaproj/aqua/pull/2830

**Comment by suzuki-shunsuke** [comment]
v2.27.2 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.27.2
