### ISSUE TITLE
cargo subcommands does not work on Windows when installing those binaries by aqua

### ISSUE THREAD

**Issue by sapphi-red** [aquaproj/aqua#2875]
### aqua info

```console
$ aqua info
{
  "version": "2.27.3",
  "commit_hash": "55503812e74e63a4ea0eeb3860840d7dce3d596d",
  "os": "windows",
  "arch": "amd64",
  "pwd": "C:\\Users\\green",
  "root_dir": "C:\\Users\\green\\AppData\\Local\\aquaproj-aqua",
  "env": {
    "AQUA_GLOBAL_CONFIG": "C:\\Users\\green\\.config\\aquaproj-aqua\\aqua.yaml"
  },
  "config_files": []
}
```

### Overview

cargo allows users to add subcommands by placing `cargo-${subcommand-name}` binary in `PATH` env var. On Linux (WSL), this feature works when installing those binaries by aqua.
But on Windows, this feature doesn't work. It doesn't work because [cargo only looks for `.exe` files](https://github.com/rust-lang/cargo/issues/10455) and [aqua places `.bat` files](https://aquaproj.github.io/docs/reference/windows-support#create-bat-files-and-shell-scripts-instead-of-symbolic-links-and-aqua-proxy).

### How to reproduce

aqua.yaml

```yaml
registries:
  - type: standard
    ref: v4.176.0
packages:
- name: crates.io/cargo-expand@1.0.86
```

Executed command and output

```console
$ cargo expand --version
error: no such command: `expand`

        View all installed commands with `cargo --list`
```

### Expected behaviour

```console
$ cargo expand --version
cargo-expand 1.0.86
```
`cargo expand` command works without error like on Linux when `cargo-expand` is installed by aqua.

### Actual behaviour

```console
$ cargo expand --version
error: no such command: `expand`

        View all installed commands with `cargo --list`
```
`cargo expand` command shows error when `cargo-expand` is installed by aqua.

### Note

I can just run the command with `cargo-expand` so it's not something urgent.

I read https://zenn.dev/shunsuke_suzuki/scraps/88e008721e748b#comment-725555a2b1b034 and understand that this is a hard problem. I'm not sure how to solve this. 😅

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
aqua creates shell scripts on bin directory but these scripts don't have file extension.
So maybe we can solve this issue by adding file extension.

https://github.com/aquaproj/aqua/blob/b86c9a1e68fb44596d665f0b654de5b7ac2de6d4/pkg/installpackage/link.go#L143

**Comment by sapphi-red** [comment]
I had a typo in my original post.

> [aqua places ~~.bin~~ .bat files](https://aquaproj.github.io/docs/reference/windows-support#create-bat-files-and-shell-scripts-instead-of-symbolic-links-and-aqua-proxy).

---

> maybe we can solve this issue by adding file extension.

Just in case, if I simply rename `C:\Users\green\AppData\Local\aquaproj-aqua\bin\cargo-expand` to `C:\Users\green\AppData\Local\aquaproj-aqua\bin\cargo-expand.exe`, I get the following error.
```
cargo expand
error: could not execute process `C:\Users\green\AppData\Local\aquaproj-aqua\bin\cargo-expand.exe expand` (never executed)

Caused by:
  このバージョンの %1 は、実行中の Windows のバージョンと互換性がありません。コンピューターのシステム情報を確認してから 、ソフトウェアの発行元に問い合わせてください。 (os error 216)
```
I guess cargo runs the file directly (= without shell).

**Comment by suzuki-shunsuke** [comment]
I see. It's hard to solve this issue.
Generally speaking, there are two approach of CLI Version Manager.

1. Use proxies to change tool versions dynamically
1. Change the environment variable `PATH` dynamically by shell

aqua adopts the first one, but I think this issue can't be solved by the first one.
The second approach is required to solve this issue.

**Comment by matzeeable** [comment]
@suzuki-shunsuke is this also the case for `docker compose`? When installing Docker and Docker Compose through aqua, the subcommand `compose` within `docker` cannot be found.

**Comment by suzuki-shunsuke** [comment]
I think the subcommand of `docker` has nothing to do with this issue.
Do you use Windows?
Could you tell me versions of aqua and Docker?

```sh
aqua info
which docker
aqua which -v docker
```

**Comment by suzuki-shunsuke** [comment]
Maybe https://github.com/aquaproj/aqua/issues/2918 is helpful for this issue.

**Comment by sapphi-red** [comment]
Yes, #2918 works for this.

If I run
```powershell
# make hard link from "aqua which cargo-expand" to "aquaproj-aqua\bin\cargo-expand.exe"
$ New-Item -ItemType HardLink -Path $env:LOCALAPPDATA\aquaproj-aqua\bin\cargo-expand.exe -Value $(aqua which cargo-expand)
```
, then `cargo expand --version` works.

**Comment by suzuki-shunsuke** [comment]
#2918 was resolved, so maybe this issue was also resolved.

**Comment by sapphi-red** [comment]
Thanks for implementing #2918! Yes, it worked.
