### ISSUE TITLE
Support `aqua rm` for `go_install` packages without `--all`

### ISSUE THREAD

**Issue by sapphi-red** [aquaproj/aqua#2905]
### Feature Overview

`aqua rm` doesn't support `go_install` packages unless `--all` is passed.
https://aquaproj.github.io/docs/guides/uninstall-packages/#limitation

It would be nice if `aqua rm` supports removing `go_install` packages without requiring `--all`.

### Why is the feature needed?

When I try some packages that is `go_install` type and decided not to use it, I want to remove the binaries to save storage space.

### Workaround

- manually finding the binary and removing it
  - `aqua rm` is easier
- run `aqua rm --all`
  - I'll have to install packages again

### Note

refs https://github.com/orgs/aquaproj/discussions/2903
refs https://github.com/aquaproj/aqua/issues/538

**Comment by suzuki-shunsuke** [comment]
📝 

https://github.com/aquaproj/aqua/blob/4ba02d7a202d20bed54c35471842bd255fe46e25/pkg/controller/remove/remove.go#L157-L162

https://github.com/aquaproj/aqua/blob/4ba02d7a202d20bed54c35471842bd255fe46e25/pkg/config/registry/package_info.go#L636-L646

https://github.com/aquaproj/aqua/blob/4ba02d7a202d20bed54c35471842bd255fe46e25/pkg/config/package.go#L91-L96

**Comment by suzuki-shunsuke** [comment]
I remembered why we didn't support this feature.

`go_install`'s `path` can depend on a version.

e.g.

https://aquaproj.github.io/docs/reference/registry-config/go-install-package

```yaml
path: github.com/volatiletech/sqlboiler/v{{(semver .Version).Major}}
```

To uninstall a package, aqua must be able to detect a file path to be removed independent of version.

In the above example, it's `github.com/volatiletech/sqlboiler` but it's difficult to detect the path programatically.

To resolve this issue, my idea is to add a field to detect a file path to be removed.

```yaml
# TODO: decide the field name
# package_dir, base_dir
removed_dir: github.com/volatiletech/sqlboiler
```

Using this field, we can uninstall not only `go_install` type packages but also `http` type packages.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/3101

**Comment by suzuki-shunsuke** [comment]
v2.33.0 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.33.0

This release supports not only `go_install` but also `http` packages.
Furthermore, we could resolve this issue without adding a new field.

https://github.com/aquaproj/aqua/issues/2905#issuecomment-2119018187

> To resolve this issue, my idea is to add a field to detect a file path to be removed.
