### ISSUE TITLE
Use hard links on Windows instead of batch files

### ISSUE THREAD

**Issue by futsuuu** [aquaproj/aqua#2918]
### Feature Overview

Hard links work without developer mode and administrator permissions unlike symbolic links on Windows.

### Why is the feature needed?

1. batch file is slow
2. unneeded prompt `Terminate batch job (Y/N)?` will be shown on `Ctrl-C`

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I'm not familiar with Windows and Hard link on Windows, but it's interesting.

Maybe Hard link is useful to solve https://github.com/aquaproj/aqua/issues/2875 .
aqua uses shell scripts and bat files, but this can cause some troubles.

**Comment by sapphi-red** [comment]
I tried this out by the following steps and it seems to work. I'm not sure if there's any edge cases though.

1. Clone https://github.com/aquaproj/aqua-proxy
2. Open that directory
3. Run `aqua i`
4. Add `cmdName, _ = strings.CutSuffix(cmdName, ".exe")` after this line: https://github.com/aquaproj/aqua-proxy/blob/a0c37569b7752c23aa57bd1b054a791b70fb2891/pkg/cli/proxy.go#L25
5. Run `go build .\cmd\aqua-proxy\`
6. Make hard link from `./aqua-proxy.exe` to `cmdx.exe` (Run `New-Item -ItemType HardLink -Path cmdx.exe -Value ./aqua-proxy.exe` if you're using powershell)
7. Run `./cmdx.exe --version`. cmdx worked correctly.
8. Edit https://github.com/aquaproj/aqua-proxy/blob/a0c37569b7752c23aa57bd1b054a791b70fb2891/aqua/cmdx.yaml#L2 to use different version
9. Run `aqua update-checksum`
10. Run  `./cmdx.exe --version`. The different version was downloaded and cmdx worked correctly.

I tried the steps above with powershell, but I also tried running `./cmdx.exe --version` with cmd and git bash and it worked.

**Comment by W1M0R** [comment]
Maybe this will resolve an issue I am having.

I have go 1.22.5 installed globally (via scoop) and go 1.22.4 installed locally (via aqua). As you can see in the `PATH`, aqua packages should have precedence before scoop packages.

See the following output:

```pwsh
$ cat .\aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.197.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.22.4

$ Write-Host $Env:PATH
# PATH output is redacted to show the important parts and ordering
PATH=C:\Users\user2\AppData\Local\aquaproj-aqua\bat;C:\Users\user2\go\bin;C:\Users\user2\scoop\shims

$ go version
# I didn't expect the global (scoop) version of go to be used.
go version go1.22.5 windows/amd64

$ go.bat version
# It shouldn't be necessary to use the .bat extension to force the local (aqua) version of go.
go version go1.22.4 windows/amd64
```

According to [these remarks](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/path#remarks):

> The Windows operating system searches using default file name extensions in the following order of precedence: .exe, .com, .bat, and .cmd. Which means if you're looking for a batch file named, acct.bat, but have an app named acct.exe in the same directory, you must include the .bat extension at the command prompt.

This also has useful information: https://stackoverflow.com/questions/1653472/whats-the-relative-order-with-which-windows-search-for-executable-files-in-path

My `PATHEXT` variable is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL`. This is the default on my machine and I don't want to change it.

**Comment by W1M0R** [comment]
I really like what the aqua project has accomplished and the tool is a very good contribution to the Windows ecosystem. Unfortunately, the current approach using `bat` files is problematic in many ways (ctrl-c and signal forwarding) and makes the aqua experience on Windows average.

It looks like proto has a good solution to this issue, and very helpful PRs that explain the issue in detail and how to resolve it:

1. https://github.com/moonrepo/proto/blob/de3803ef40b1982a36722d8f088505246e4eb19d/crates/cli/src/main_shim.rs#L4
2. https://github.com/moonrepo/proto/pull/315
3. https://github.com/moonrepo/proto/issues/269

Hope this helps!

**Comment by suzuki-shunsuke** [comment]
I'm working on this.

**Comment by suzuki-shunsuke** [comment]
The prerelease version [v2.30.0-1](https://github.com/aquaproj/aqua/releases/tag/v2.30.0-1) is out.
Could you try this and give us your feedback?

I've tested using Git Bash for Windows, Powershell, and Command Prompt on Windows.

Update aqua by `aqua upa`.

```sh
aqua upa v2.30.0-1
```

If `aqua upa` doesn't work well, you can use `aqua-installer`.

```sh
aqua-installer v2.30.0-1
```

Run `aqua i -l`, then aqua-proxy would be installed, bat directory would be removed, and shell scripts on `bin` directory would be removed and hard links would be created on `bin` directory.

```sh
aqua i -l
```

**Comment by W1M0R** [comment]
Yes, I'll give it a try and get back to you.

**Comment by suzuki-shunsuke** [comment]
I'm working on fixing an issue.

https://github.com/aquaproj/aqua-registry/actions/runs/9953893071/job/27498390778#step:4:225

```
FATA[0000] aqua failed                                   aqua_version=2.30.0-1 env=windows/amd64 error="install aqua-proxy: remove a file to replace it with a hard link: remove C:\\Users\\runneradmin\\AppData\\Local\\aquaproj-aqua\\bin\\aqua.exe: Access is denied." program=aqua
```

**Comment by W1M0R** [comment]
I can confirm that it works on my end. Thanks @suzuki-shunsuke!

My `PATH`:

```pwsh
$Env:PATH = @(
    (Join-Path $Env:PROTO_HOME "shims")
    (Join-Path $Env:PROTO_HOME "bin")
    (Join-Path $Env:AQUA_ROOT_DIR "bin")
    (Join-Path $Env:USERPROFILE "scoop/shims")
    $Env:PATH
) -join [IO.Path]::PathSeparator
```

My `aqua.yaml`:

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.204.0  # renovate: depName=aquaproj/aqua-registry
packages:
- name: charmbracelet/glow@v1.5.1
- name: charmbracelet/gum@v0.14.1
```

The output:

```pwsh
❯ aqua i -l
INFO[0000] creating a hard link to aqua-proxy            aqua_version=2.30.0-1 command=glow env=windows/amd64 program=aqua
INFO[0000] creating a hard link to aqua-proxy            aqua_version=2.30.0-1 command=gum env=windows/amd64 program=aqua

❯ gcm gum | select source

Source
------
C:\Users\user2\AppData\Local\aquaproj-aqua\bin\gum.exe

❯ gum --version            
INFO[0000] download and unarchive the package            aqua_version=2.30.0-1 env=windows/amd64 exe_name=gum package_name=charmbracelet/gum package_version=v0.14.1 program=aqua registry=standard
WARN[0002] remove a temporal file                        aqua_version=2.30.0-1 env=windows/amd64 error="remove C:\\Users\\user2\\AppData\\Local\\Temp\\178831399: The process cannot access the file because it is being used by another process." exe_name=gum package_name=charmbracelet/gum package_version=v0.14.1 program=aqua registry=standard
gum version v0.14.1 (657c76e)
```

**Comment by suzuki-shunsuke** [comment]
Thank you.
I've published the prerelease version v2.30.0-3.

I'll take a look at the warning.

```
WARN[0002] remove a temporal file                        aqua_version=2.30.0-1 env=windows/amd64 error="remove C:\\Users\\user2\\AppData\\Local\\Temp\\178831399: The process cannot access the file because it is being used by another process." exe_name=gum package_name=charmbracelet/gum package_version=v0.14.1 program=aqua registry=standard
```

**Comment by suzuki-shunsuke** [comment]
v2.30.0 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.30.0

**Comment by W1M0R** [comment]
Thank you for the great work you are doing!
