### ISSUE TITLE
Generate completions for fish shell

### ISSUE THREAD

**Issue by reitzig** [aquaproj/aqua#2927]
### Feature Overview

`aqua completion` should support argument `fish`, outputting fish code that can be sourced or written to a completion file.

### Why is the feature needed?

fish is a popular shell in some circles.

### Workaround

There is no workaround: bash/zsh completion is utterly incompatible with the fish way of doing completions.

### Example Code

```console
$ aqua completion fish | source
```

should enable fish completion in the current shell.

### Note

While undocumented, urface/cli seems to implement fish completions: [urfave/cli#351](https://github.com/urfave/cli/issues/351), [urfave/cli#848](https://github.com/urfave/cli/pull/848), [smallstep/cli#708](https://github.com/smallstep/cli/pull/708/files)

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

https://pkg.go.dev/github.com/urfave/cli/v2#App.ToFishCompletion
https://github.com/aquaproj/aqua/blob/d38c23777116c9773f074ef0fc76d723d452260a/pkg/cli/completion.go

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/2929

**Comment by suzuki-shunsuke** [comment]
I published the prerelease version v2.29.0-1.

https://github.com/aquaproj/aqua/releases/tag/v2.29.0-1

Could you confirm v2.29.0-1?

```sh
aqua upa v2.29.0-1
```

**Comment by reitzig** [comment]
Can confirm: The command generates a valid fish script (tested with fish 3.10, rather old 🙈) that provides (some) completions:
![image](https://github.com/aquaproj/aqua/assets/4246780/85ecc550-9fe5-488f-9fd2-5cb201dd2a02)

Completion doesn't seem to be perfect (note the suggested folder which I _think_ shouldn't be there):
![image](https://github.com/aquaproj/aqua/assets/4246780/c1045b9f-f97d-44c2-92b4-93dc95ce2573)
Whether that's a problem with the library, or with your use of it, I couldn't say.

In fact, on an empty prompt there's no proposal at all:
![image](https://github.com/aquaproj/aqua/assets/4246780/366c8d39-3ae3-4967-8f24-0e71b800fab6)
Expected would be something like this:
![image](https://github.com/aquaproj/aqua/assets/4246780/22667c52-c6b8-4a82-af0c-e7ff70bd6a41)
Most of the Go tools I've installed seem to use [spf13/viper](https://github.com/spf13/viper) so maybe I'm just spoiled. 😅

Anyway, thanks for the lightning-fast resolution, much appreciated! 👏 🫶

**Comment by suzuki-shunsuke** [comment]
Thank you for confirming!

**Comment by suzuki-shunsuke** [comment]
v2.29.0 is out 🎉

https://github.com/aquaproj/aqua/releases/tag/v2.29.0
