### ISSUE TITLE
Failure to install using `go install`

### ISSUE THREAD

**Issue by ryoha000** [aquaproj/aqua#3017]
## Description

I encountered an issue when trying to install `aqua` using the following command:
```
$ go install github.com/aquaproj/aqua/v2/cmd/aqua@latest
```

The installation fails with the following error message:
```
go: github.com/aquaproj/aqua/v2/cmd/aqua@latest (in github.com/aquaproj/aqua/v2@v2.30.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

I believe the cause of this issue is the `replace` directive present in the current `go.mod` file in the main branch. The specific line is:
```
replace github.com/urfave/cli/v2 v2.27.2 => github.com/urfave/cli/v2 v2.27.3-0.20240629214313-84c536d83870
```

## Steps to Reproduce
Run the following command in the terminal:
```
go install github.com/aquaproj/aqua/v2/cmd/aqua@latest
```

## Environment
go version: go1.22.5
os: Ubuntu 20.04.3
cpu: x86_64

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
The `replace` directive was introduced to solve the issue of shell completion.

- https://github.com/lintnet/lintnet/issues/528
- https://github.com/aquaproj/aqua/pull/2981

Could you install aqua by another way?

https://aquaproj.github.io/docs/install

**Comment by ryoha000** [comment]
Thank you for your prompt response and the detailed explanation.

I have successfully installed aqua using an alternative method as suggested in the documentation. My primary intention was to report that the installation method using `go install`, which is currently documented, does not work due to the `replace` directive issue.

Thank you again for your assistance and for your continued efforts to improve `aqua`.

**Comment by suzuki-shunsuke** [comment]
This issue will be solved at the next release.

urfave/cli/v2 v2.27.3 was out, so we don't have to use `replace` directive anymore.

- https://github.com/aquaproj/aqua/pull/3024

**Comment by suzuki-shunsuke** [comment]
v2.31.0 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.31.0
