### ISSUE TITLE
Add a comment for schema validation when generating configuration files

### ISSUE THREAD

**Issue by mpal9000** [aquaproj/aqua#3202]
### Feature Overview

When generating files with the CLI, e.g. `aqua init` or `aqua generate-registry` a comment could be added on top of the file, for schema validation via the editor's YAML language server. The comment could be added under `---`, but works above as well.

Also an additional schema for "aqua-policy.yaml" could be added to "json-schema" repo and used as above.

See:
https://aquaproj.github.io/docs/reference/config/#json-schema
https://aquaproj.github.io/docs/reference/registry-config/#json-schema

### Why is the feature needed?

For better user experience when editing the configurations manually.

### Example Code

aqua.yaml

```yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json

# ...
```

aqua-registry.yaml

```yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json

# ...
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
Do you have any refefence abaout the comment `# yaml-language-server: $schema=`?
I'm looking for it.

**Comment by suzuki-shunsuke** [comment]
I'm wondering if this comment syntax is common for editors such as VSCode, Vim, Neovim, and so on.

**Comment by mpal9000** [comment]
https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#using-inlined-schema
I'm using neovim and https://github.com/b0o/SchemaStore.nvim (https://github.com/SchemaStore/schemastore) can also be used.
So your schemas could also be registred to https://github.com/SchemaStore/schemastore. Other editors have plugins to pick schemas from that registry.

**Comment by suzuki-shunsuke** [comment]
Done.
