### ISSUE TITLE
Add option to filter packages for aqua update: --{exclude-}tags

### ISSUE THREAD

**Issue by mlavi** [aquaproj/aqua#3393]
### Feature Overview

I can conditionally install a subset of commands by using Aqua package tags, so I would like to update the same subset by tags.

### Why is the feature needed?

I've adopted [aqua's package tags](https://aquaproj.github.io/docs/guides/package-tag/) for installation (described in `aqua install --help`), so I would like to also use tags for updates, but `aqua update --help` shows no such options.

### Example Code

To only update packages with the tag: bootstrap

```console
$ aqua install --all --tags bootstrap
$ aqua --config "${AQUA_GLOBAL_CONFIG}" --tags bootstrap update
```

Configuration is already specified, e.g.:

```yaml
---
packages:
- name: direnv/direnv@v2.35.0
  tags:
    - bootstrap
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!
I'm working on this.

- https://github.com/aquaproj/aqua/issues/3393

**Comment by suzuki-shunsuke** [comment]
@mlavi Could you try https://github.com/aquaproj/aqua/releases/tag/v2.41.0-0 ?

```sh
aqua upa v2.41.0-0
aqua up -t bootstrap # Update only packages with a tag `bootstrap`
aqua up --exclude-tags bootstrap # Exclude packages with a tag `bootstrap`
```

**Comment by suzuki-shunsuke** [comment]
🎉 https://github.com/aquaproj/aqua/releases/tag/v2.41.0

**Comment by mlavi** [comment]
@suzuki-shunsuke I apologize I could not test until today, thank you so much for the rapid response and feature development!

` aqua --config "${AQUA_GLOBAL_CONFIG}"  update --tags bootstrap`  and --exclude-tags both work perfectly with my test using version 2.42.2 today!
