### ISSUE TITLE
Support "aqua remove" or "aqua clean" - removing package

### ISSUE THREAD

**Issue by borley1211** [aquaproj/aqua#538]
```diff
---
  # aqua - Declarative CLI Version Manager
  # https://aquaproj.github.io/
  registries:
  - type: standard
    ref: v0.13.1 # renovate: depName=aquaproj/aqua-registry

  packages:
  - name: cli/cli@v2.2.0
- - name: junegunn/fzf@0.28.0
```

```console
$ aqua clean  # remove package automatically
```

**Comment by suzuki-shunsuke** [comment]
https://aquaproj.github.io/docs/reference/clean

**Comment by suzuki-shunsuke** [comment]
We have no plan to support this.
If the directory becomes huge, you can clean it by yourself.
https://aquaproj.github.io/docs/reference/clean

**Comment by suzuki-shunsuke** [comment]
> ```diff
> ---
>   # aqua - Declarative CLI Version Manager
>   # https://aquaproj.github.io/
>   registries:
>   - type: standard
>     ref: v0.13.1 # renovate: depName=aquaproj/aqua-registry
> 
>   packages:
>   - name: cli/cli@v2.2.0
> - - name: junegunn/fzf@0.28.0
> ```
> 
> ```
> $ aqua clean  # remove package automatically
> ```

To support this feature, aqua has to manage the history of aqua.yaml.

**Comment by borley1211** [comment]
Surely that's difficult... Sorry.

**Comment by suzuki-shunsuke** [comment]
No problem. Thank you for your proposal.

**Comment by borley1211** [comment]
Perhaps a command like `aqua cleanup`, which can reset the environment in one operation, might be more useful.

**Comment by suzuki-shunsuke** [comment]
I'm reconsidering this feature.
If we aim to enable to delete packages flexibly, the command usage, specification, and implementation will get complicated.
This is not desirable for both users and maintainers.

Even if you remove packages, Lazy Install will reinstall them when they are necessary, so we don't need to support deleting packages so flexibly.

So I'm thinking the simple features like the following.

```console
$ aqua rm --all # Delete all packages (delete `pkgs` but keep `bin`)
$ aqua rm [<registry name>,]<package name> [...] # Delete given packages (delete all versions)
$ aqua rm --command [-c] <command name> # Delete packages with the given command (delete all versions)
```

About packages, aqua refers `registries` in aqua.yaml. Even if they aren't used in `packages` aqua can remove them.
About command, aqua refers `packages` in aqua.yaml.

`rm` command doesn't edit `aqua.yaml`, which means it doesn't remove packages from `packages` in aqua.yaml.
It also doesn't remove symbolic links from the bin directory.

You may want to keep the latest version and delete only old versions, but we don't support it now.
Lazy Install will reinstall the latest version.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/2249

**Comment by suzuki-shunsuke** [comment]
v2.11.0 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.11.0

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/issues/2251
