### ISSUE TITLE
AQUA_GLOBAL_CONFIG is not working

### ISSUE THREAD

**Issue by budimanjojo** [aquaproj/aqua#567]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 0.10.2 (67b6b2275c891af25b7182ff74c6745303c390f9)

```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): Ubuntu 20.04
* CPU Architecture (amd64, arm64, etc): amd64

## How to reproduce

I did this: https://aquaproj.github.io/docs/tutorial-basics/global-config. When I do aqua commands, it gives me this error:
```
 aqua g
FATA[0000] aqua failed                                   aqua_version=0.10.2 error="configuration file isn't found" program=aqua

```

## References

*

**Comment by suzuki-shunsuke** [comment]
It's strange.
In my environment, AQUA_GLOBAL_CONFIG works well.

Please confirm if the environment variable is set and configuration files exist.

```
$ echo $AQUA_GLOBAL_CONFIG
```

**Comment by suzuki-shunsuke** [comment]
Oh, I got it.
`aqua g` command doesn't check global configuration.

**Comment by suzuki-shunsuke** [comment]
I'll add the description to https://aquaproj.github.io/docs/tutorial-basics/global-config
Thank you for your feedback.

**Comment by budimanjojo** [comment]
Thanks, looks like setting `AQUA_CONFIG` is better than `AQUA_GLOBAL_CONFIG`. I wonder what is the use case of global.

**Comment by budimanjojo** [comment]
I thought `AQUA_GLOBAL_CONFIG` is like the default config file when there is no `aqua.yaml` file in the current directory. Seems like I'm wrong. Now that I have set `AQUA_CONFIG`, will aqua use the `aqua.yaml` file if it exists and only use the path of `AQUA_CONFIG` when there's no `aqua.yaml` file in the pwd?

**Comment by suzuki-shunsuke** [comment]
https://aquaproj.github.io/docs/reference/config#configuration-file-path

`AQUA_CONFIG` has the highest priority, and is used by all aqua sub commands.

We assume that `AQUA_GLOBAL_CONFIG` is set in shell configuration file such as `.bash_profile`,
and `AQUA_CONFIG` is used in the specific project.

e.g. .envrc https://github.com/direnv/direnv

```
export AQUA_CONFIG=$PWD/aqua.yaml
```

**Comment by budimanjojo** [comment]
So, global config is what I should be using theoretically, but I can't run any command except those two commands. Which is quite weird.
Sorry, but I think what I need is a default config. Here's what I want:
- When there is no `aqua.yaml` file in current `pwd`, use the default config
- When there is an `aqua.yaml` file in current `pwd`, use `aqua.yaml`
So, is there any way I can do this? Thank you

**Comment by suzuki-shunsuke** [comment]
You can execute tools in the global configuration.

https://aquaproj.github.io/docs/tutorial-basics/global-config

`aqua g` is used to search tools and add them to configuration file.

e.g.

```
$ aqua g >> aqua.yaml
```

If you want to add tools in global configuration, change the current directory and run `aqua g`.

**Comment by budimanjojo** [comment]
Thanks for the answers, I think I know what I should be doing, I'll close this issue
