### ISSUE TITLE
Exec performance regression

### ISSUE THREAD

**Issue by adamcstephens** [aquaproj/aqua#582]
## aqua version

main branch

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): Linux
* CPU Architecture (amd64, arm64, etc): amd64

## How to reproduce

Use main branch aqua.yaml from there. exec/which any command. With a global config set, it can take even longer to scan multiple files.

```
─❯ time ./aqua.out exec actionlint >/dev/null
________________________________________________________
Executed in    1.01 secs    fish           external
   usr time    2.66 secs  385.00 micros    2.66 secs
   sys time    0.17 secs   63.00 micros    0.17 secs
```

Previously on v1.0.0

```
time ./aqua.out exec actionlint >/dev/null
________________________________________________________
Executed in   43.05 millis    fish           external
   usr time  121.10 millis  372.00 micros  120.73 millis
   sys time   66.82 millis   62.00 micros   66.75 millis
```

## Expected Behaviour

Quick exec response.

## Actual Behaviour

Unfortunately, 1-2 second which/exec lookups.

## Important Factoids

I bisected v1.0.0 to main and the regression commit was https://github.com/aquaproj/aqua/commit/26fe124f45ed7010bbe01750b650638a28d76a41 . This commit only fixed config reading, likely due to the yaml library switch which appears to be the underlying cause.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

I'll investigate the issue.

I compared v1.1.0-0 with v1.0.0, then there may be a performance regression as you say.

```console
$ aqua v
aqua version 1.1.0-1 (29095a314be902a216d0eec145cd0e3c0dc08e1f)
```

```console
$ time /opt/homebrew/bin/aqua exec gh version
gh version 2.5.1 (2022-02-15)
https://github.com/cli/cli/releases/tag/v2.5.1
/opt/homebrew/bin/aqua exec gh version  0.08s user 0.02s system 104% cpu 0.095 total

$ time ~/bin/aqua exec gh version
gh version 2.5.1 (2022-02-15)
https://github.com/cli/cli/releases/tag/v2.5.1
~/bin/aqua exec gh version  1.86s user 0.11s system 327% cpu 0.605 total
```

**Comment by suzuki-shunsuke** [comment]
TODO: Benchmark `readConfig`

https://github.com/aquaproj/aqua/blob/29095a314be902a216d0eec145cd0e3c0dc08e1f/pkg/controller/config.go#L180-L193

1. goccy/go-yaml
2. gopkg.in/yaml.v2

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.1.0-2
Please confirm the issue has been solved.

**Comment by adamcstephens** [comment]
I can confirm that this has been solved. Thanks for the quick fix!
