### ISSUE TITLE
[Feature Request] Generate json schema for registry from Go structs

### ISSUE THREAD

**Issue by 4513ECHO** [aquaproj/aqua#623]
## Feature Overview

Generate json schema to validate registry files.

## Why is the feature needed?

> Please explain the problem you want to solve.

We can write registry with in yaml. It is declarative, but writing correctly has been difficult a bit lately. I want help of editor.

I suggest to give out [json schema](https://json-schema.org/). It defines structure of json-like lanuage (yaml or toml), and it can be used by language server. It is useful for completion or linting, so we can develop registry more easily.

Also, generated schema should be served on the website (https://aquaproj.github.io is suitable)

Ready-made projects to do that:

- https://github.com/xeipuuv/gojsonschema
- https://github.com/mcuadros/go-jsonschema-generator
- https://github.com/invopop/jsonschema

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ 
```

```yaml

```

**Comment by 4513ECHO** [comment]
It is kind in registry to add parameter than adding custom templates.
String is hard to validate for linter or language server.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

I use JSON Schema in the other project and I think it's useful.

* https://github.com/suzuki-shunsuke/tfaction/blob/main/schema/tfaction-root.json
* https://suzuki-shunsuke.github.io/tfaction/config/tfaction-root.html
* https://github.com/coveooss/json-schema-for-humans

In the above case, I maintain JSON Schema manually, but it's useful to generate JSON Schema from Go.

**Comment by suzuki-shunsuke** [comment]
* https://github.com/xeipuuv/gojsonschema/issues/344

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/624

**Comment by suzuki-shunsuke** [comment]
Generate JSON Schema and push them to https://github.com/aquaproj/aquaproj.github.io/tree/gh-pages/docs/json-schema
when a commit is pushed to this repository's main branch.

**Comment by suzuki-shunsuke** [comment]
Unfortunately, json-schema-for-humans doesn't support JSON Schema 2020-12.
https://github.com/coveooss/json-schema-for-humans/issues/131#issuecomment-1072431355

**Comment by suzuki-shunsuke** [comment]
* https://aquaproj.github.io/json-schema/aqua-yaml.json
* https://aquaproj.github.io/json-schema/registry.json

**Comment by suzuki-shunsuke** [comment]
Hmm...
Maybe `https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json` is better than GitHub Pages in terms of versioning.

**Comment by suzuki-shunsuke** [comment]
* https://github.com/aquaproj/aqua/tree/main/json-schema
* https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
* https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json

**Comment by suzuki-shunsuke** [comment]
I've removed the repository aquaproj/json-schema.

**Comment by suzuki-shunsuke** [comment]
I found a bug with JSON Schema. 🙂
https://github.com/aquaproj/aqua-registry/pull/2777

**Comment by suzuki-shunsuke** [comment]
Document

* https://github.com/aquaproj/aqua/pull/627
* https://github.com/aquaproj/aquaproj.github.io/pull/65

**Comment by 4513ECHO** [comment]
Schema looks nice. Linting works correctly on my editor. However I have one suggest.
I think the properties of `replacements` should be possible values of `GOOS`.
In the same way, `goos` and `goarch` of `(format_)overrides` should be enum of posiible values of `GOOS`/`GOARCH`.
It is more useful for validating.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
It makes sense.

https://pkg.go.dev/runtime#pkg-constants

> GOARCH is the running program's architecture target: one of 386, amd64, arm, s390x, and so on.
> GOOS is the running program's operating system target: one of darwin, freebsd, linux, and so on.
> To view possible combinations of GOOS and GOARCH, run "go tool dist list".

```console
$ go tool dist list
```

<details>

```
aix/ppc64
android/386
android/amd64
android/arm
android/arm64
darwin/amd64
darwin/arm64
dragonfly/amd64
freebsd/386
freebsd/amd64
freebsd/arm
freebsd/arm64
illumos/amd64
ios/amd64
ios/arm64
js/wasm
linux/386
linux/amd64
linux/arm
linux/arm64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/riscv64
linux/s390x
netbsd/386
netbsd/amd64
netbsd/arm
netbsd/arm64
openbsd/386
openbsd/amd64
openbsd/arm
openbsd/arm64
openbsd/mips64
plan9/386
plan9/amd64
plan9/arm
solaris/amd64
windows/386
windows/amd64
windows/arm
windows/arm64
```

</details>

**Comment by suzuki-shunsuke** [comment]
```console
$ go tool dist list | xargs dirname | sort -u
aix
android
darwin
dragonfly
freebsd
illumos
ios
js
linux
netbsd
openbsd
plan9
solaris
windows
```

```console
$ go tool dist list | xargs basename | sort -u
386
amd64
arm
arm64
mips
mips64
mips64le
mipsle
ppc64
ppc64le
riscv64
s390x
wasm
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/628

**Comment by suzuki-shunsuke** [comment]
Test standard registry with JSON Schema. https://github.com/aquaproj/aqua-registry/pull/2779
