### ISSUE TITLE
[Feature Request] Allow set dummy OS/Arch value for testing

### ISSUE THREAD

**Issue by 4513ECHO** [aquaproj/aqua#643]
## Feature Overview

Add the new way to make testing other environment more
easily.

## Why is the feature needed?

> Please explain the problem you want to solve.

Aqua is the cross-platform project and support many platform, so when we add new packages to registry, we have to think of other environment.

For example linux-arm64 is not popular platform, but we have to think of support of it. Also, some developers have to think of support of darwin even they don't have mac.

So, I suggest the way to test other platform with dummy OS/Arch.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

I will think what is the best way.
My ideas are here:

```console
Set value on command line
$ GOARCH=arm64 aqua i --test
Set value on command line (another sample)
$ AQUAOS=darwin aqua i --test
Add new parameter
$ aqua i --test --os darwin --arch amd64
Add new parameter (another sample)
$ aqua i --test --env GOARCH amd64 --env GOOS linux
```

```yaml

```

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal. It makes sense.

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/644

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.4.0-0

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua-registry/pull/3024

**Comment by suzuki-shunsuke** [comment]
Document: https://github.com/aquaproj/aquaproj.github.io/pull/69

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.4.0 has been released.
