### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#850]
## Feature Overview

Currently, aqua doesn't support Windows.
It is desirable for aqua to support Windows.

I don't have Windows, so I'm not familiar with Windows.
And it is a little difficult to verify aqua on Windows.

There are differences between Windows and Linux, so we have to solve some problems.

* https://github.com/aquaproj/aqua/blob/a7b5c0f1f51f9c94a975b033060ffa997be2bfe0/pkg/controller/which/lookpath.go#L13-L29
* https://github.com/aquaproj/aqua/blob/a7b5c0f1f51f9c94a975b033060ffa997be2bfe0/pkg/exec/exec.go#L11

We also have to fix [aqua-registry](https://github.com/aquaproj/aqua-registry) to support Windows.

## Why is the feature needed?

> Please explain the problem you want to solve.

Windows is most popular OS, so the Windows support may make aqua more popular.

## Does the feature include Breaking Changes?

Probably no, but we have to investigate it.

## Example Code

Nothing.

**Comment by suzuki-shunsuke** [comment]
I didn't know this function.
https://pkg.go.dev/path/filepath#SplitList

**Comment by suzuki-shunsuke** [comment]
# Install Path (AQUA_ROOT_DIR)

XDG Base Directory doesn't match Windows.

**Comment by 4513ECHO** [comment]
If we support windows, almost all of `supported_if` which value is  `not (GOOS == "linux" and GOARCH == "arm64")` in aqua-registry should be rewritten.
Because its actual meaning is "the package only supports `amd64`, but `darwin` with `rosetta2` is also working."
So we have to replace like below:

```yaml
supported_if: GOARCH == "amd64" or GOOS == "darwin"
```

**Comment by 4513ECHO** [comment]
We can use [adrg/xdg](https://github.com/adrg/xdg) to handle XDG Base Directory Specification even on Windows and simplify logics.

> Go implementation of the XDG Base Directory Specification and XDG user directories

**Comment by suzuki-shunsuke** [comment]
> If we support windows, almost all of `supported_if` which value is `not (GOOS == "linux" and GOARCH == "arm64")` in aqua-registry should be rewritten. Because its actual meaning is "the package only supports `amd64`, but `darwin` with `rosetta2` is also working." So we have to replace like below:
> 
> ```yaml
> supported_if: GOARCH == "amd64" or GOOS == "darwin"
> ```

Hmm...
I think basically there is no difference between two expressions except for Windows ARM64.

`not (GOOS == "linux" and GOARCH == "arm64")`

GOOS | GOARCH | result
--- | --- | ---
windows | amd64 | true
windows | arm64 | true
darwin | - | true
linux | amd64 | true
linux | arm64 | false

`GOARCH == "amd64" or GOOS == "darwin"`

GOOS | GOARCH | result
--- | --- | ---
windows | amd64 | true
windows | arm64 | false
darwin | - | true
linux | amd64 | true
linux | arm64 | false

**Comment by suzuki-shunsuke** [comment]
> We can use [adrg/xdg](https://github.com/adrg/xdg) to handle XDG Base Directory Specification even on Windows and simplify logics.
> 
> > Go implementation of the XDG Base Directory Specification and XDG user directories

Oh, thank you.

**Comment by suzuki-shunsuke** [comment]
I got a Windows Server by [Amazon Workspaces](https://aws.amazon.com/workspaces/).

Expectedly, it failed to build aqua on Windows.

```console
$ go build -o dist/aqua ./cmd/aqua
pkg\exec\exec.go:36:14: undefined: unix.Exec
```

https://github.com/aquaproj/aqua/blob/a7b5c0f1f51f9c94a975b033060ffa997be2bfe0/pkg/exec/exec.go#L35-L37

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/issues/850#issuecomment-1153199772 was solved by #852

**Comment by suzuki-shunsuke** [comment]
`aqua init` and `aqua list` work, but `aqua g` doesn't work on Windows.

<img width="122" alt="image" src="https://user-images.githubusercontent.com/13323303/173241421-4dc0061f-7f39-471a-8770-a335e6553609.png">

**Comment by suzuki-shunsuke** [comment]
# Check List

command | status | note
--- | --- | ---
aqua help | :white_check_mark: |
aqua version | :white_check_mark: |
aqua --help | :white_check_mark: |
aqua --version | :white_check_mark: |
aqua init | :white_check_mark: |
aqua list | :white_check_mark: |
aqua which gh | :x: | freeze
aqua g -i cli/cli | :white_check_mark: |
aqua g cli/cli | :white_check_mark: |
aqua g | :x: | freeze
aqua i -l | :x: | freeze
aqua i -l -a | |
aqua i | |
aqua exec -- gh version | |

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/853
https://github.com/suzuki-shunsuke/go-findconfig/pull/208

**Comment by suzuki-shunsuke** [comment]
`aqua g` doesn't work on Windows.
I found an issue of go-fuzzyfinder.
https://github.com/ktr0731/go-fuzzyfinder/issues/2#issuecomment-467051194

> There will be blocking problems when executing programs on git bash or goland ide.
> I changed bash to execute successfully. Thank you very much.

**Comment by suzuki-shunsuke** [comment]
## Fix Standard Registry

* https://github.com/aquaproj/aqua-registry/pull/3942

**Comment by suzuki-shunsuke** [comment]
# :bulb: Allow aqua to create symbolic links

aqua creates symbolic links, so you have to allow aqua to create symbolic links.
In Windows, you may encounter some issues about symbolic links.
Please solve yourself.

**Comment by suzuki-shunsuke** [comment]
Maybe aqua should set the suffix `.exe` by default if GOOS is `windows`.

**Comment by suzuki-shunsuke** [comment]
📝 

The log message isn't colorized.

* Git Bash

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13323303/173285793-28fdacb6-9bcd-4390-8f78-5d584980a021.png">

**Comment by suzuki-shunsuke** [comment]
package | done | windows support | note
--- | --- | --- | ---
1xyz/pryrite | [ ] | | | 
99designs/aws-vault | [ ] | | | 
Aloxaf/silicon | [ ] | | | 
Arriven/db1000n | [ ] | | | 
Azure/aks-engine | [ ] | | | 
Azure/aztfy | [ ] | | | 
BeryJu/korb | [ ] | | | 
BurntSushi/ripgrep | [ ] | | | 
Cian911/switchboard | [ ] | | | 
CircleCI-Public/circleci-cli | [ ] | | | 
ClementTsang/bottom | [ ] | | | 
Dreamacro/clash | [ ] | | | 
FairwindsOps/nova | [ ] | | | 
FairwindsOps/pluto | [ ] | | | 
FairwindsOps/polaris | [ ] | | | 
FairwindsOps/rbac-lookup | [ ] | | | 
FiloSottile/age | [ ] | | | 
FiloSottile/mkcert | [ ] | | | 
GoodwayGroup/gwvault | [ ] | | | 
GoogleCloudPlatform/terraformer | [ ] | | | 
GoogleCloudPlatform/terraformer/aws | [ ] | | | 
GoogleContainerTools/container-diff | [ ] | | | 
GoogleContainerTools/container-structure-test | [ ] | | | 
GoogleContainerTools/kpt | [ ] | | | 
GoogleContainerTools/skaffold | [ ] | | | 
Jeffail/benthos | [ ] | | | 
Kong/deck | [ ] | | | 
Ladicle/kubectl-rolesum | [ ] | | | 
LukeChannings/deno-arm64 | [ ] | | | 
MusicDin/kubitect | [ ] | | | 
Peltoche/lsd | [ ] | | | 
Praqma/helmsman | [ ] | | | 
Schniz/fnm | [ ] | | | 
Shopify/ejson | [ ] | | | 
Songmu/ecschedule | [ ] | | | 
Songmu/ghch | [ ] | | | 
Songmu/ghg | [ ] | | | 
Songmu/gocredits | [ ] | | | 
Songmu/gotesplit | [ ] | | | 
Songmu/goxz | [ ] | | | 
Songmu/horenso | [ ] | | | 
SpectralOps/teller | [ ] | | | 
TheZoraiz/ascii-image-converter | [ ] | | | 
TimothyYe/skm | [ ] | | | 
TomWright/dasel | [ ] | | | 
Traackr/binnacle | [ ] | | | 
Trendyol/kink | [ ] | | | 
Versent/saml2aws | [ ] | | | 
XAMPPRocky/tokei | [ ] | | | 
abiosoft/colima | [ ] | | | 
abs-lang/abs | [ ] | | | 
accurics/terrascan | [ ] | | | 
aelsabbahy/goss | [ ] | | | 
aelsabbahy/goss/dcgoss | [ ] | | | 
aelsabbahy/goss/dgoss | [ ] | | | 
aelsabbahy/goss/kgoss | [ ] | | | 
ahmetb/kubectl-tree | [ ] | | | 
ahmetb/kubectx | [ ] | | | 
ahmetb/kubectx/kubens | [ ] | | | 
ahmetb/kubens | [ ] | | | 
ajeetdsouza/zoxide | [ ] | | | 
alexellis/arkade | [ ] | | | 
alexellis/k3sup | [ ] | | | 
amacneil/dbmate | [ ] | | | 
anchore/grype | [ ] | | | 
anchore/syft | [ ] | | | 
anqiansong/github-compare | [ ] | | | 
antonmedv/fx | [ ] | | | 
antonmedv/llama | [ ] | | | 
apache/camel-k | [ ] | | | 
aquaproj/aqua-installer | [ ] | | | 
aquasecurity/kube-bench | [ ] | | | 
aquasecurity/kubectl-who-can | [ ] | | | 
aquasecurity/starboard | [ ] | | | 
aquasecurity/tfsec | [ ] | | | 
aquasecurity/trivy | [ ] | | | 
argoproj-labs/argocd-autopilot | [ ] | | | 
argoproj-labs/argocd-image-updater | [ ] | | | 
argoproj/argo-cd | [ ] | | | 
argoproj/argo-rollouts | [ ] | | | 
argoproj/argo-workflows | [ ] | | | 
aristocratos/btop | [ ] | | | 
arl/gitmux | [ ] | | | 
armosec/kubescape | [ ] | | | 
aws-containers/amazon-ecs-exec-checker | [ ] | | | 
aws/amazon-ec2-instance-selector | [ ] | | | 
aws/copilot-cli | [ ] | | | 
awslabs/git-secrets | [ ] | | | 
awslabs/ssosync | [ ] | | | 
b4b4r07/afx | [ ] | | | 
b4b4r07/gist | [ ] | | | 
b4b4r07/git-bump | [ ] | | | 
b4b4r07/github-labeler | [ ] | | | 
b4b4r07/gomi | [ ] | | | 
b4b4r07/iap_curl | [ ] | | | 
b4b4r07/stein | [ ] | | | 
batchcorp/plumber | [ ] | | | 
bats-core/bats-core | [ ] | | | 
bcicen/ctop | [ ] | | | 
bcicen/slackcat | [ ] | | | 
becheran/roumon | [ ] | | | 
benbjohnson/litestream | [ ] | | | 
benchkram/bob | [ ] | | | 
bengadbois/pewpew | [ ] | | | 
blacknon/hwatch | [ ] | | | 
bootandy/dust | [ ] | | | 
boz/kail | [ ] | | | 
brigadecore/brigade | [ ] | | | 
bronze1man/yaml2json | [ ] | | | 
budimanjojo/talhelper | [ ] | | | 
bufbuild/buf | [ ] | | | 
buildpacks/pack | [ ] | | | 
c-bata/kube-prompt | [ ] | | | 
caarlos0/fork-cleaner | [ ] | | | 
casey/just | [ ] | | | 
chanzuckerberg/fogg | [ ] | | | 
charmbracelet/glow | [ ] | | | 
che-incubator/chectl | [ ] | | | 
cheat/cheat | [ ] | | | 
chriswalz/bit | [ ] | | | 
civo/cli | [ ] | | | 
cli/cli | [ ] | | | 
cloudflare/cfssl | [ ] | | | 
cloudflare/cfssl/mkbundle | [ ] | | | 
cloudflare/cloudflared | [ ] | | | 
cloudfoundry/bosh-cli | [ ] | | | 
cloudfoundry/credhub-cli | [ ] | | | 
cloudposse/atmos | [ ] | | | 
cnrancher/autok3s | [ ] | | | 
codeclimate/test-reporter | [ ] | | | 
coder/coder | [ ] | | | 
codesenberg/bombardier | [ ] | | | 
compose/transporter | [ ] | | | 
containerd/nerdctl | [ ] | | | 
controlplaneio/kubesec | [ ] | | | 
corneliusweig/ketall | [ ] | | | 
corneliusweig/rakkess | [ ] | | | 
corneliusweig/rakkess/access-matrix | [ ] | | | 
cosmtrek/air | [ ] | | | 
crate-ci/typos | [ ] | | | 
create-go-app/cli | [ ] | | | 
crossplane/crossplane | [ ] | | | 
cswank/kcli | [ ] | | | 
cue-lang/cue | [ ] | | | 
cycloidio/inframap | [ ] | | | 
dagger/dagger | [ ] | | | 
dandavison/delta | [ ] | | | 
dapr/cli | [ ] | | | 
datastax-labs/astra-cli | [ ] | | | 
datreeio/datree | [ ] | | | 
ddosify/ddosify | [ ] | | | 
deepmap/oapi-codegen | [ ] | | | 
denisidoro/navi | [ ] | | | 
denoland/deno | [ ] | | | 
derailed/k9s | [ ] | | | 
derailed/popeye | [ ] | | | 
dhall-lang/dhall-haskell | [ ] | | | 
digitalocean/doctl | [ ] | | | 
direnv/direnv | [ ] | | | 
dnnrly/abbreviate | [ ] | | | 
docker-slim/docker-slim | [ ] | | | 
doitintl/kube-no-trouble | [ ] | | | 
dominikh/go-tools/staticcheck | [ ] | | | 
dotenv-linter/dotenv-linter | [ ] | | | 
ducaale/xh | [ ] | | | 
earthly/earthly | [ ] | | | 
editorconfig-checker/editorconfig-checker | [ ] | | | 
ekalinin/github-markdown-toc | [ ] | | | 
emirozer/kubectl-doctor | [ ] | | | 
env0/terratag | [ ] | | | 
ernoaapa/kubectl-warp | [ ] | | | 
errata-ai/vale | [ ] | | | 
erroneousboat/slack-term | [ ] | | | 
evilmartians/lefthook | [ ] | | | 
extrawurst/gitui | [ ] | | | 
fatedier/frp | [ ] | | | 
ffuf/ffuf | [ ] | | | 
fishi0x01/vsh | [ ] | | | 
fission/fission | [ ] | | | 
flosell/iam-policy-json-to-terraform | [ ] | | | 
fluxcd/flux2 | [ ] | | | 
fsaintjacques/semver-tool | [ ] | | | 
fujiwara/lambroll | [ ] | | | 
fujiwara/tracer | [ ] | | | 
fullstorydev/grpcurl | [ ] | | | 
gabrie30/ghorg | [ ] | | | 
gcla/termshark | [ ] | | | 
genuinetools/img | [ ] | | | 
genuinetools/reg | [ ] | | | 
geofffranks/spruce | [ ] | | | 
getsentry/sentry-cli | [ ] | | | 
getzola/zola | [ ] | | | 
ginuerzh/gost | [ ] | | | 
git-chglog/git-chglog | [ ] | | | 
git-lfs/git-lfs | [ ] | | | 
github/hub | [ ] | | | 
gleam-lang/gleam | [ ] | | | 
go-jira/jira | [ ] | | | 
go-task/task | [ ] | | | 
gocruncher/jenkins-job-cli | [ ] | | | 
gohugoio/hugo | [ ] | | | 
gojuno/minimock | [ ] | | | 
gokcehan/lf | [ ] | | | 
golang-migrate/migrate | [ ] | | | 
golang.org/x/perf/cmd/benchstat | [ ] | | | 
golang.org/x/tools/cmd/goimports | [ ] | | | 
golang/go | [ ] | | | 
golang/mock | [ ] | | | 
golang/tools/gopls | [ ] | | | 
golangci/golangci-lint | [ ] | | | 
goodwithtech/dockle | [ ] | | | 
google/go-containerregistry | [ ] | | | 
google/go-jsonnet | [ ] | | | 
google/jsonnet | [ ] | | | 
google/ko | [ ] | | | 
google/pprof | [ ] | | | 
google/wire | [ ] | | | 
gopasspw/gopass | [ ] | | | 
goreleaser/goreleaser | [ ] | | | 
goreleaser/nfpm | [ ] | | | 
gotestyourself/gotestsum | [ ] | | | 
grafana/k6 | [ ] | | | 
grafana/loki/logcli | [ ] | | | 
grafana/tanka | [ ] | | | 
grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway | [ ] | | | 
grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2 | [ ] | | | 
grpc/grpc-go/protoc-gen-go-grpc | [ ] | | | 
gruntwork-io/kubergrunt | [ ] | | | 
gruntwork-io/terragrunt | [ ] | | | 
gsamokovarov/jump | [ ] | | | 
hadolint/hadolint | [ ] | | | 
hairyhenderson/gomplate | [ ] | | | 
harelba/q | [ ] | | | 
harness/drone-cli | [ ] | | | 
hashicorp/consul | [ ] | | | 
hashicorp/go-getter | [ ] | | | 
hashicorp/levant | [ ] | | | 
hashicorp/nomad | [ ] | | | 
hashicorp/packer | [ ] | | | 
hashicorp/terraform | [ ] | | | 
hashicorp/terraform-ls | [ ] | | | 
hashicorp/terraform-plugin-docs | [ ] | | | 
hashicorp/vault | [ ] | | | 
hashicorp/waypoint | [ ] | | | 
haskell/cabal/cabal-install | [ ] | | | 
haskell/ghcup-hs | [ ] | | | 
hasura/graphql-engine | [ ] | | | 
helm/chart-releaser | [ ] | | | 
helm/helm | [ ] | | | 
hidetatz/kubecolor | [ ] | | | 
high-moctane/nextword | [ ] | | | 
homeport/dyff | [ ] | | | 
iawia002/lux | [ ] | | | 
im2nguyen/rover | [ ] | | | 
incu6us/goimports-reviser | [ ] | | | 
influxdata/influx-cli | [ ] | | | 
infracost/infracost | [ ] | | | 
inlets/inlets-pro | [ ] | | | 
inlets/inletsctl | [ ] | | | 
instrumenta/kubeval | [ ] | | | 
int128/ghcp | [ ] | | | 
int128/kauthproxy | [ ] | | | 
int128/kubectl-external-forward | [ ] | | | 
int128/kubelogin | [ ] | | | 
int128/yamlpatch | [ ] | | | 
iovisor/kubectl-trace | [ ] | | | 
istio/istio/istioctl | [ ] | | | 
itchyny/gojq | [ ] | | | 
itchyny/mmv | [ ] | | | 
ivanilves/lstags | [ ] | | | 
jamesob/desk | [ ] | | | 
jenkins-zh/jenkins-cli | [ ] | | | 
jesseduffield/horcrux | [ ] | | | 
jesseduffield/lazydocker | [ ] | | | 
jesseduffield/lazygit | [ ] | | | 
jetstack/cert-manager/cmctl | [ ] | | | 
johanhaleby/kubetail | [ ] | | | 
jonaslu/ain | [ ] | | | 
joshdk/retry | [ ] | | | 
jreleaser/jreleaser | [ ] | | | 
jreleaser/jreleaser/standalone | [ ] | | | 
jsonnet-bundler/jsonnet-bundler | [ ] | | | 
juliosueiras/terraform-lsp | [ ] | | | 
junegunn/fzf | [ ] | | | 
k0sproject/k0s | [ ] | | | 
k0sproject/k0sctl | [ ] | | | 
kanisterio/kanister | [ ] | | | 
kastenhq/external-tools/k10multicluster | [ ] | | | 
kastenhq/external-tools/k10tools | [ ] | | | 
kastenhq/kubestr | [ ] | | | 
katbyte/terrafmt | [ ] | | | 
kayac/ecspresso | [ ] | | | 
kdabir/has | [ ] | | | 
knative/client | [ ] | | | 
knqyf263/cob | [ ] | | | 
knqyf263/pet | [ ] | | | 
knqyf263/utern | [ ] | | | 
koalaman/shellcheck | [ ] | | | 
kool-dev/kool | [ ] | | | 
kreuzwerker/awsu | [ ] | | | 
kreuzwerker/envplate | [ ] | | | 
kreuzwerker/m1-terraform-provider-helper | [ ] | | | 
ktr0731/evans | [ ] | | | 
kubecost/kubectl-cost | [ ] | | | 
kubemq-io/kubemqctl | [ ] | | | 
kubernetes-sigs/cluster-api | [ ] | | | 
kubernetes-sigs/kind | [ ] | | | 
kubernetes-sigs/krew | [ ] | | | 
kubernetes-sigs/kubebuilder | [ ] | | | 
kubernetes-sigs/kubefed | [ ] | | | 
kubernetes-sigs/kustomize | [ ] | | | 
kubernetes/kompose | [ ] | | | 
kubernetes/kops | [ ] | | | 
kubernetes/kubectl | [ ] | | | 
kubernetes/minikube | [ ] | | | 
kudobuilder/kuttl | [ ] | | | 
kvaps/kubectl-node-shell | [ ] | | | 
kyleconroy/sqlc | [ ] | | | 
kyoh86/richgo | [ ] | | | 
lc/gau | [ ] | | | 
liamg/extrude | [ ] | | | 
liamg/gitjacker | [ ] | | | 
liamg/memit | [ ] | | | 
liamg/pax | [ ] | | | 
liamg/scout | [ ] | | | 
liamg/traitor | [ ] | | | 
lima-vm/lima | [ ] | | | 
livebud/bud | [ ] | | | 
loft-sh/devspace | [ ] | | | 
loft-sh/vcluster | [ ] | | | 
lotabout/skim | [ ] | | | 
magefile/mage | [ ] | | | 
mantil-io/mantil | [ ] | | | 
marcosnils/bin | [ ] | | | 
mattn/gof | [ ] | | | 
mattn/goreman | [ ] | | | 
mattn/memo | [ ] | | | 
megaease/easeprobe | [ ] | | | 
mercari/tfnotify | [ ] | | | 
mergestat/mergestat | [ ] | | | 
mikefarah/yq | [ ] | | | 
miku/zek | [ ] | | | 
minamijoyo/hcledit | [ ] | | | 
minamijoyo/tfmigrate | [ ] | | | 
minamijoyo/tfschema | [ ] | | | 
minamijoyo/tfupdate | [ ] | | | 
minishift/minishift | [ ] | | | 
mitchellh/gox | [ ] | | | 
mkchoi212/fac | [ ] | | | 
mongodb/mongocli | [ ] | | | 
mozilla/sops | [ ] | | | 
mszostok/codeowners-validator | [ ] | | | 
muesli/duf | [ ] | | | 
mumoshu/variant | [ ] | | | 
mumoshu/variant2 | [ ] | | | 
mvdan/gofumpt | [ ] | | | 
mvdan/sh | [ ] | | | 
nektos/act | [ ] | | | 
neovim/neovim | [ ] | | | 
newrelic/newrelic-cli | [ ] | | | 
nikochiko/autosaved | [ ] | | | 
noborus/trdsql | [ ] | | | 
nojima/httpie-go | [ ] | | | 
norwoodj/helm-docs | [ ] | | | 
npryce/adr-tools | [ ] | | | 
oam-dev/kubevela | [ ] | | | 
oam-dev/kubevela/kubectl-plugin | [ ] | | | 
ogham/dog | [ ] | | | 
ogham/exa | [ ] | | | 
okteto/okteto | [ ] | | | 
open-policy-agent/conftest | [ ] | | | 
open-policy-agent/opa | [ ] | | | 
openfaas/faas-cli | [ ] | | | 
operator-framework/operator-sdk | [ ] | | | 
orf/gping | [ ] | | | 
orisano/dlayer | [ ] | | | 
ossf/scorecard | [ ] | | | 
ozankasikci/dockerfile-generator | [ ] | | | 
particledecay/kconf | [ ] | | | 
peak/s5cmd | [ ] | | | 
peco/peco | [ ] | | | 
pglet/pglet | [ ] | | | 
pivotal-cf/om | [ ] | | | 
pivotal-cf/pivnet-cli | [ ] | | | 
plexsystems/sinker | [ ] | | | 
porter-dev/porter | [ ] | | | 
postfinance/kubectl-sudo | [ ] | | | 
pressly/goose | [ ] | | | 
profclems/glab | [ ] | | | 
projectdiscovery/httpx | [ ] | | | 
projectdiscovery/naabu | [ ] | | | 
projectdiscovery/nuclei | [ ] | | | 
projectdiscovery/subfinder | [ ] | | | 
protocolbuffers/protobuf-go/protoc-gen-go | [ ] | | | 
pulumi/kubespy | [ ] | | | 
pulumi/pulumi | [ ] | | | 
rancher/cli | [ ] | | | 
rancher/k3d | [ ] | | | 
rancher/kim | [ ] | | | 
rancher/rke | [ ] | | | 
rclone/rclone | [ ] | | | 
rebuy-de/aws-nuke | [ ] | | | 
replicatedhq/kots | [ ] | | | 
replicatedhq/outdated | [ ] | | | 
restic/restic | [ ] | | | 
reviewdog/reviewdog | [ ] | | | 
rhysd/actionlint | [ ] | | | 
rhysd/hgrep | [ ] | | | 
rikatz/kubepug | [ ] | | | 
rlmcpherson/s3gof3r | [ ] | | | 
roboll/helmfile | [ ] | | | 
robscott/kube-capacity | [ ] | | | 
rogerwelin/cassowary | [ ] | | | 
ropnop/kerbrute | [ ] | | | 
rs/curlie | [ ] | | | 
rust-lang/mdBook | [ ] | | | 
ryane/kfilt | [ ] | | | 
s0md3v/Smap | [ ] | | | 
sachaos/viddy | [ ] | | | 
sahilm/yamldiff | [ ] | | | 
sanathp/statusok | [ ] | | | 
sbstp/kubie | [ ] | | | 
scaleway/scaleway-cli | [ ] | | | 
schollz/croc | [ ] | | | 
sclevine/yj | [ ] | | | 
segmentio/chamber | [ ] | | | 
sethvargo/ratchet | [ ] | | | 
sharkdp/bat | [ ] | | | 
sharkdp/diskus | [ ] | | | 
sharkdp/fd | [ ] | | | 
sharkdp/hexyl | [ ] | | | 
sharkdp/hyperfine | [ ] | | | 
sharkdp/pastel | [ ] | | | 
sheepla/fzwiki | [ ] | | | 
sheepla/qiitaz | [ ] | | | 
shellspec/shellspec | [ ] | | | 
siderolabs/conform | [ ] | | | 
siderolabs/talos | [ ] | | | 
siderolabs/theila | [ ] | | | 
sigstore/cosign | [ ] | | | 
sigstore/gitsign | [ ] | | | 
sigstore/rekor | [ ] | | | 
six-ddc/plow | [ ] | | | 
slackhq/nebula | [ ] | | | 
slok/sloth | [ ] | | | 
snyk/driftctl | [ ] | | | 
spinnaker/spin | [ ] | | | 
sqshq/sampler | [ ] | | | 
squat/kilo | [ ] | | | 
stackrox/kube-linter | [ ] | | | 
starship/starship | [ ] | | | 
stedolan/jq | [ ] | | | 
stepchowfun/docuum | [ ] | | | 
stern/stern | [ ] | | | 
sumneko/lua-language-server | [ ] | | | 
suzuki-shunsuke/akoi | [ ] | | | 
suzuki-shunsuke/asciinema-trim | [ ] | | | 
suzuki-shunsuke/checkout-merged-branch-with-ci-info | [ ] | | | 
suzuki-shunsuke/ci-info | [ ] | | | 
suzuki-shunsuke/ci-renovate-config-validator | [ ] | | | 
suzuki-shunsuke/circleci-config-merge | [ ] | | | 
suzuki-shunsuke/cmdx | [ ] | | | 
suzuki-shunsuke/dd-time | [ ] | | | 
suzuki-shunsuke/discussion-slack-notifier | [ ] | | | 
suzuki-shunsuke/durl | [ ] | | | 
suzuki-shunsuke/git-rm-branch | [ ] | | | 
suzuki-shunsuke/github-comment | [ ] | | | 
suzuki-shunsuke/matchfile | [ ] | | | 
suzuki-shunsuke/renovate-issue-action | [ ] | | | 
suzuki-shunsuke/tfcmt | [ ] | | | 
suzuki-shunsuke/yaml2json | [ ] | | | 
swaggo/swag | [ ] | | | 
sysdiglabs/kube-psp-advisor | [ ] | | | 
talos-systems/conform | [ ] | | | 
talos-systems/talos | [ ] | | | 
tcnksm/ghr | [ ] | | | 
tektoncd/cli | [ ] | | | 
telepresenceio/telepresence | [ ] | | | 
temporalio/temporal | [ ] | | | 
terraform-docs/terraform-docs | [ ] | | | 
terraform-linters/tflint | [ ] | | | 
tfmigrator/cli | [ ] | | | 
tfutils/tfenv | [ ] | | | 
thazelart/terraform-validator | [ ] | | | 
thought-machine/please | [ ] | | | 
tilt-dev/ctlptl | [ ] | | | 
tilt-dev/tilt | [ ] | | | 
timdp/lwc | [ ] | | | 
tinygo-org/tinygo | [ ] | | | 
tkuchiki/alp | [ ] | | | 
tmccombs/hcl2json | [ ] | | | 
tomnomnom/gron | [ ] | | | 
trufflesecurity/driftwood | [ ] | | | 
trufflesecurity/trufflehog | [ ] | | | 
tsenart/vegeta | [ ] | | | 
twpayne/chezmoi | [ ] | | | 
up9inc/mizu | [ ] | | | 
uptrace/uptrace | [ ] | | | 
uw-labs/strongbox | [ ] | | | 
variantdev/vals | [ ] | | | 
vektra/mockery | [ ] | | | 
vi/websocat | [ ] | | | 
vmware-tanzu/carvel-imgpkg | [ ] | | | 
vmware-tanzu/carvel-kapp | [ ] | | | 
vmware-tanzu/carvel-kbld | [ ] | | | 
vmware-tanzu/carvel-kwt | [ ] | | | 
vmware-tanzu/carvel-vendir | [ ] | | | 
vmware-tanzu/carvel-ytt | [ ] | | | 
vmware-tanzu/octant | [ ] | | | 
vmware-tanzu/velero | [ ] | | | 
wader/fq | [ ] | | | 
wagoodman/dive | [ ] | | | 
watchexec/watchexec | [ ] | | | 
weaveworks/eksctl | [ ] | | | 
webdevops/go-crond | [ ] | | | 
windvalley/gossh | [ ] | | | 
wtfutil/wtf | [ ] | | | 
x-motemen/ghq | [ ] | | | 
xiecat/fofax | [ ] | | | 
xitonix/trubka | [ ] | | | 
xo/usql | [ ] | | | 
xtaci/kcptun | [ ] | | | 
xwjdsh/manssh | [ ] | | | 
yannh/kubeconform | [ ] | | | 
ycd/dstp | [ ] | | | 
yohamta/dagu | [ ] | | | 
zaquestion/lab | [ ] | | | 
zegl/kube-score | [ ] | | | 
zellij-org/zellij | [ ] | | | 
ziglang/zig | [ ] | | | 
zix99/rare | [ ] | | | 
zricethezav/gitleaks | [ ] | | |

**Comment by suzuki-shunsuke** [comment]
# gnu vs msvc

I'm not familiar with Windows and Rust.
I'll have to investigate it.

## Reference

* https://github.com/extendr/rextendr/issues/19

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/858

**Comment by suzuki-shunsuke** [comment]
We have to support disabling auto completion of the suffix ".exe".
https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.21

[terraformer-all-windows-amd64](https://github.com/GoogleCloudPlatform/terraformer/releases/download/0.8.21/terraformer-all-windows-amd64)

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.11.0-0

**Comment by suzuki-shunsuke** [comment]
Maybe we have to fix aqua-installer for Windows.

https://minosjp.hatenablog.com/entry/2020/12/30/201515
https://docs.github.com/en/actions/learn-github-actions/environment-variables

> If the workflow specified a Windows runner, you would use the syntax for PowerShell, $env:NAME. For more information about shells, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsshell)."

**Comment by suzuki-shunsuke** [comment]
I'll fix this error.

```
get the unarchiver or decompressor by the file extension:
get the unarchiver or decompressor by the file extension: format unrecognized by
 filename: goss-alpha-windows-amd64.exe
```

**Comment by suzuki-shunsuke** [comment]
I'll fix this error.

```
time="2022-06-14T19:10:49+09:00" level=fatal msg="aqua failed" aqua_version= env=windows/amd64 error="get the registry configurat
ion file by Get GitHub Content API: GET https://api.github.com/repos/aelsabbahy/goss/contents/extras/dcgoss/dcgoss.exe?ref=v0.3.1
8: 404 Not Found []" program=aqua
```

**Comment by suzuki-shunsuke** [comment]
🤔  It failed to run dcgoss.

aelsabbahy/goss/dcgoss

```console
$ aqua exec -- dcgoss --help
time="2022-06-15T04:45:46Z" level=fatal msg="aqua failed" aqua_version= env=windows/amd64 error="it failed to start the process"
program=aqua
```

**Comment by suzuki-shunsuke** [comment]
Installed tools were removed by Windows Security.
I guess you have to fix the configuration of Security Softwares properly.

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/issues/883

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/issues/850#issuecomment-1153118272

aqua depends on the environment variable `HOME` and `XDG_DATA_HOME`.

https://aquaproj.github.io/docs/reference/config/#environment-variables

> AQUA_ROOT_DIR: (default: ${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua)

https://github.com/adrg/xdg 

* XDG_DATA_HOME: `%LOCALAPPDATA%`
* HOME: `%USERPROFILE%`

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/issues/885
https://github.com/aquaproj/aqua/issues/887

**Comment by suzuki-shunsuke** [comment]
Created. https://github.com/orgs/aquaproj/projects/4

**Comment by suzuki-shunsuke** [comment]
# Give up supporting tools written in shell scripts on Windows for now

I'll exclude windows by `supported_if` (`supported_envs`).
If there are feature requests, I'll reconsider to support them.

* aelsabbahy/goss/dcgoss
* aelsabbahy/goss/dgoss
* aelsabbahy/goss/kgoss
* aquaproj/aqua-installer
* aws-containers/amazon-ecs-exec-checker
* awslabs/git-secrets
* bats-core/bats-core
* ekalinin/github-markdown-toc
* fsaintjacques/semver-tool
* postfinance/kubectl-sudo
* tfutils/tfenv
* etc
