### ISSUE TITLE
Shell completion for aqua commands

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua#856]
## Feature Overview

Please provide a command like `aqua completion bash` to generate the shell completion script for each shell. This seems to be easily achievable with:
https://cli.urfave.org/v2/#bash-completion

## Why is the feature needed?

> Please explain the problem you want to solve.

Many cli tools provide `completion <shell>` command for users. It's highly convenient to have it with aqua too.

## Does the feature include Breaking Changes?

I don't think so.

## Example Code

> command and configuration

Once it's provided, users would run a command like this to set up their shell completions:

```console
$ source <(aqua completion bash)
```

Thank you!

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

**Comment by suzuki-shunsuke** [comment]
> Many cli tools provide completion <shell> command for users.

Could you tell us some examples?

**Comment by tadayosi** [comment]
Yes, sure. For instance, k8s related cli tools such as `kubectl`, `kn`, `helm`, and `stern` have `completion <shell>` or similar subcommands. Eg.
```sh
kubectl completion bash
```
outputs bash completion script that users can use for their environments.

**Comment by suzuki-shunsuke** [comment]
I see. Thank you for your explanation. It looks good.

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua/releases/tag/v1.11.0
Thank you for your contribution.

**Comment by tadayosi** [comment]
@suzuki-shunsuke Thank you!
