### ISSUE TITLE
Local registry path in aqua.yaml doesn't support `~` or `$HOME` notation

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua#901]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.11.0 (8cb3ef2ca56dc98f38920422a137c1f17150a069)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): Linux -- Fedora release 36 (Thirty Six)
* CPU Architecture (amd64, arm64, etc): amd64

## Overview

I wanted to put a local registry in the home directory but found that a notation like `path: ~/local-registry.yaml` or `path: $HOME/local-registry.yaml` in `aqua.yaml` is not supported.

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
registries:
- type: standard
  ref: v2.28.0 # renovate: depName=aquaproj/aqua-registry
- name: local
  type: local
  path: ~/local-registry.yaml
```

```console
$ aqua g
ERRO[0000] install the registry                          aqua_version=1.11.0 env=linux/amd64 error="local registry isn't found" local_registry_file_path="/home/tasato/~/local-registry.yaml" program=aqua registry_name=local
FATA[0000] aqua failed                                   aqua_version=1.11.0 env=linux/amd64 error="it failed to install some packages" program=aqua

```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ $ AQUA_LOG_LEVEL=debug aqua g
ERRO[0000] install the registry                          aqua_version=1.11.0 env=linux/amd64 error="local registry isn't found" local_registry_file_path="/home/tasato/~/local-registry.yaml" program=aqua registry_name=local
FATA[0000] aqua failed                                   aqua_version=1.11.0 env=linux/amd64 error="it failed to install some packages" program=aqua

```

## Expected Behaviour

- aqua should find the local registry file relative to my home directory

## Actual Behaviour

- it throws error and stop working

## Important Factoids

n/a

## References

* n/a

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.

**Comment by suzuki-shunsuke** [comment]
* https://pkg.go.dev/os#ExpandEnv
* https://stackoverflow.com/questions/7922270/obtain-users-home-directory/13004756#13004756

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/902

**Comment by suzuki-shunsuke** [comment]
I've recreated a pull request.

- https://github.com/aquaproj/aqua/pull/1416

**Comment by suzuki-shunsuke** [comment]
I've confirmed #1416 works well.

```yaml
registries:
- name: local
  type: local
  path: $HOME/.config/aquaproj-aqua/registry.yaml
```

**Comment by suzuki-shunsuke** [comment]
Published a prerelease version. https://github.com/aquaproj/aqua/releases/tag/v1.25.0-0

```console
$ aqua update-aqua v1.25.0-0
```

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua/releases/tag/v1.25.0
