### ISSUE TITLE
[Windows] Colorize the output on Git Bash

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#916]
## Feature Overview

Colorize the output on Git Bash.

## Why is the feature needed?

> Please explain the problem you want to solve.

To make the output easy to understand.
It makes the log level clear.

## Does the feature include Breaking Changes?

No.

## Reference

https://pkg.go.dev/github.com/sirupsen/logrus#section-readme

> Nicely color-coded in development (when a TTY is attached, otherwise just plain text):

Maybe this is a problem of Windows Setting, not a problem of aqua.

**Comment by 4513ECHO** [comment]
You can use [mattn/go-colorable](https://github.com/mattn/go-colorable).

**Comment by suzuki-shunsuke** [comment]
Thank you for your advice!
I'll try it. #917

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.13.0
