### ISSUE TITLE
[Feature Request] Add option to control colored output

### ISSUE THREAD

**Issue by 4513ECHO** [aquaproj/aqua#982]
## Feature Overview

Add `--color={never|auto|always}` option to control colored output.

## Why is the feature needed?

> Please explain the problem you want to solve.

Sometimes I want non-colored log to process for example writing to files or editing with awk/sed. Also, I want to see colored log on GitHub Action, but aqua automatically disable colored output. I want to control colored output.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
maybe global option is useful than environmet variable
$ aqua --color=always install --test
```

```yaml

```

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

**Comment by suzuki-shunsuke** [comment]
https://github.com/sirupsen/logrus

> Nicely color-coded in development (when a TTY is attached, otherwise just plain text):

```go
log.SetFormatter(&log.TextFormatter{
		DisableColors: true,
	})
```

**Comment by suzuki-shunsuke** [comment]
```console
$ export AQUA_COLOR=false # Disable color
```

```console
$ export AQUA_COLOR=true # Force color
```

**Comment by suzuki-shunsuke** [comment]
```console
$ export AQUA_LOG_COLOR=always # never|auto|always
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/983

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.17.0-0

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/releases/tag/v1.17.0
