### ISSUE TITLE
Is there a way to provide a GitHub API token for aqua?

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua#987]
Sometimes I've been interacting with GitHub too much using aqua and get the rate limit exceed errors:
> $ aqua gr operator-framework/operator-registry
> WARN[0000] list release assets                           aqua_version=1.17.0 env=linux/amd64 error="GET https://api.github.com/repos/operator-framework/operator-registry/releases/71077824/assets?per_page=100: 403 API rate limit of 60 still exceeded until 2022-07-04 20:16:52 +0900 JST, not making remote request. [rate reset in 38m49s]" program=aqua repo_name=operator-registry repo_owner=operator-framework

My understanding is that providing a custom GitHub API token would mitigate the issue.
Is there a way to provide a GitHub API token for aqua?

**Comment by suzuki-shunsuke** [comment]
https://aquaproj.github.io/docs/reference/config#environment-variables

> AQUA_GITHUB_TOKEN, GITHUB_TOKEN: GitHub Access Token. This is required to install private repository's package

**Comment by tadayosi** [comment]
@suzuki-shunsuke Thank you!  This is exactly what I'd been looking for.

Talking about documentation, I don't think this is accurate. The env vars are important (not to say required) when you interact with public repositories only. You'll hit the limit when you run `aqua g -i` many times in a short period of time. 

> This is required to install private repository's package

What about creating FAQ section in the doc and listing potential issues/questions users might face like this one?

**Comment by suzuki-shunsuke** [comment]
Good suggestion.
There is the page [Trouble Shooting](https://aquaproj.github.io/docs/trouble-shooting), but the content isn't adequate.
